-- Keep ATELIER core data behind the server-side service role.
-- The public roles are not part of ATELIER authentication and must not read or
-- write merchant, identity, session, or workflow tables through PostgREST.
revoke all on table
  appointment_advisor_services,
  appointment_advisors,
  appointment_business_hours,
  appointment_import_runs,
  appointment_services,
  appointment_settings,
  appointments,
  assets,
  audit_events,
  customer_events,
  customer_memberships,
  customer_notes,
  customer_points_accounts,
  customer_points_ledger,
  customer_tag_links,
  customer_tags,
  customers,
  legacy_imports,
  license_codes,
  license_redemptions,
  membership_levels,
  membership_programs,
  memberships,
  merchant_ai_connections,
  merchant_ai_policies,
  merchant_sessions,
  operator_sessions,
  operator_users,
  orders,
  plan_catalog,
  resource_store_assignments,
  resources,
  schema_migrations,
  staff_leaves,
  staff_members,
  staff_schedules,
  staff_store_assignments,
  stores,
  subscriptions,
  tenants,
  users,
  workflow_definitions,
  workflow_event_consumptions,
  workflow_events,
  workflow_instances,
  workflow_tasks,
  workflow_versions,
  workspace_configs,
  workspace_media_folders,
  workspaces
from anon, authenticated;

revoke execute on function public.atelier_create_appointment(
  uuid, uuid, uuid, text, text, text, text, uuid, uuid, uuid,
  timestamptz, text, text, text, text
) from anon, authenticated;
