// Generated by PRIVLAN Commerce Studio. Edit the homepage in the admin panel.
Page({
  data: {
    "navPadTop": 20,
    "channels": [
        "??",
        "LAKE MAGGIORE"
    ],
    "channel": "??",
    "pageTitle": "系列活动",
    "cartItems": [],
    "cartSummary": {
        "quantity": 0,
        "price": 0
    },
    "serviceBot": {
        "enabled": true,
        "icon": "/images/icon-headset.png",
        "size": 88,
        "right": 110,
        "bottom": 475
    },
    "block0Hotspots": [],
    "block0": [
        {
            "id": "slide-msjzktea-9zkt",
            "kind": "image",
            "src": "/images/d5f9cfe54e41e6dda2cf77987cb75749.jpg",
            "title": "",
            "subtitle": "",
            "buttonText": "????",
            "showContent": false,
            "showButton": false,
            "linkType": "page",
            "linkValue": "/pages/category/category",
            "duration": 5,
            "poster": "/images/d5f9cfe54e41e6dda2cf77987cb75749.jpg",
            "order": 0,
            "hotspots": []
        },
        {
            "id": "slide-mshcjlje-0z1x",
            "kind": "image",
            "src": "/images/hero2.jpg",
            "title": "LAKE MAGGIORE",
            "subtitle": "??????",
            "buttonText": "????",
            "showContent": true,
            "showButton": true,
            "linkType": "page",
            "linkValue": "/pages/category/category",
            "duration": 5,
            "poster": "",
            "order": 1,
            "hotspots": []
        }
    ],
    "block0Autoplay": false,
    "block0Interval": 6000,
    "block1Hotspots": [],
    "block2Hotspots": [],
    "block2": []
},
  onLoad() {
    const win = wx.getWindowInfo ? wx.getWindowInfo() : wx.getSystemInfoSync();
    const menu = wx.getMenuButtonBoundingClientRect();
    this.setData({ navPadTop: menu.top || win.statusBarHeight || 20 });
  },
  onShow() {
    if (typeof this.getTabBar === "function" && this.getTabBar()) this.getTabBar().setData({ selected: 2 });
  },
  switchChannel(e) { this.setData({ channel: e.currentTarget.dataset.c }); },
  onSearch() { wx.showToast({ title: "搜索功能演示", icon: "none" }); },
  heroAction(e) {
    const type = e.currentTarget.dataset.linkType;
    const value = e.currentTarget.dataset.linkValue;
    if (!value) return;
    const clean = value.split("?")[0];
    const tabs = ["/pages/home/home", "/pages/category/category", "/pages/campaign/campaign", "/pages/cart/cart", "/pages/mine/mine"];
    if (tabs.includes(clean)) wx.switchTab({ url: clean });
    else if (type === "external") wx.navigateTo({ url: "/pages/webview/webview?url=" + encodeURIComponent(value) });
    else wx.navigateTo({ url: value });
  },
  mediaAction(e) { this.heroAction(e); },
  benefitAction(e) { this.heroAction(e); },
  hotspotAction(e) { this.heroAction(e); },
  explore() { wx.switchTab({ url: "/pages/category/category" }); },
  goDetail(e) { wx.navigateTo({ url: "/pages/detail/detail?id=" + e.currentTarget.dataset.id }); },
  goBack() { wx.navigateBack({ fail: () => wx.switchTab({ url: "/pages/home/home" }) }); },
  addCart() { cart.add(null); this.refreshCart(); wx.showToast({ title: "已加入购物车", icon: "success" }); },
  buyNow() { cart.add(null); wx.switchTab({ url: "/pages/cart/cart" }); }
});
