const crypto = require("node:crypto");

function uuid() { return crypto.randomUUID(); }
function scopeValues(scope) { return [scope.tenantId, scope.workspaceId, scope.storeId]; }
function maskPhone(phone) { const value = String(phone || ""); return value.length >= 7 ? value.slice(0, 3) + "****" + value.slice(-4) : value; }
function anonymousName(id) { return "微信用户 " + String(id || "").replace(/-/g, "").slice(0, 4).toUpperCase(); }

function createCustomerService({ db, openIdHashKey = process.env.ATELIER_OPENID_HASH_KEY || "", tagRepository = null }) {
  if (!db) throw new Error("database is required");
  function hashOpenId(openid) {
    if (Buffer.byteLength(openIdHashKey) < 32) throw Object.assign(new Error("预约身份服务尚未配置"), { status: 503, code: "OPENID_HASH_KEY_MISSING" });
    if (!String(openid || "")) throw Object.assign(new Error("缺少可信微信身份"), { status: 401, code: "AUTH_REQUIRED" });
    return crypto.createHmac("sha256", openIdHashKey).update(String(openid || "")).digest("hex");
  }
  async function appendEvent(tx, scope, customerId, type, source, resourceType = null, resourceId = null, metadata = {}) {
    await tx.query("insert into customer_events(id,tenant_id,workspace_id,store_id,customer_id,event_type,source,resource_type,resource_id,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb) on conflict do nothing", [uuid(), ...scopeValues(scope), customerId, type, source, resourceType, resourceId, JSON.stringify(metadata || {})]);
  }
  async function audit(tx,scope,action,resourceType,resourceId,metadata={}){await tx.query("insert into audit_events(id,tenant_id,workspace_id,actor_type,actor_id,action,resource_type,resource_id,request_id,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb)",[uuid(),scope.tenantId,scope.workspaceId,scope.actorType||"merchant",scope.userId||scope.actorId||"system",action,resourceType,resourceId||null,scope.requestId||uuid(),JSON.stringify(metadata)]);}
  async function ensureDefaults(tx,scope){await tx.query("insert into membership_programs(id,tenant_id,workspace_id,store_id,enabled,points_enabled) values($1,$2,$3,$4,false,false) on conflict(tenant_id,workspace_id,store_id) do nothing",[uuid(),...scopeValues(scope)]);await tx.query("insert into membership_levels(id,tenant_id,workspace_id,store_id,name,level_order,growth_threshold,enabled) values($1,$2,$3,$4,'普通会员',1,0,true) on conflict(tenant_id,workspace_id,store_id,level_order) do nothing",[uuid(),...scopeValues(scope)]);}
  async function findOrCreateCustomer(tx, scope, input = {}) {
    const hash = input.openidHash || hashOpenId(input.openid);
    const name = String(input.name || "").trim().slice(0, 120) || null;
    const phone = String(input.phone || "").trim().slice(0, 40) || null;
    const source = ["mini_program", "merchant_manual", "import", "order", "appointment"].includes(input.source) ? input.source : "mini_program";
    const existing = (await tx.query("select id,tenant_id,store_id from customers where tenant_id=$1 and workspace_id=$2 and wechat_openid_hash=$3 for update", [scope.tenantId, scope.workspaceId, hash])).rows[0];
    if (existing && String(existing.store_id) !== String(scope.storeId)) throw Object.assign(new Error("客户身份已绑定其他门店"), { status: 409, code: "CUSTOMER_SCOPE_CONFLICT" });
    const displayName = String(input.displayName || name || "").trim().slice(0, 120) || null;
    const result = await tx.query("insert into customers(id,tenant_id,workspace_id,store_id,source,name,phone,display_name,avatar_url,wechat_openid_hash,first_seen_at,last_seen_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,now(),now()) on conflict(workspace_id,wechat_openid_hash) do update set name=coalesce(excluded.name,customers.name),phone=coalesce(excluded.phone,customers.phone),display_name=coalesce(excluded.display_name,customers.display_name),avatar_url=coalesce(excluded.avatar_url,customers.avatar_url),last_seen_at=now(),updated_at=now() returning *", [uuid(), ...scopeValues(scope), source, name, phone, displayName, input.avatarUrl || null, hash]);
    const customer = result.rows[0];
    const eventType = existing ? "mini_program_seen" : "mini_program_first_seen";
    const eventKey = `${eventType}:${customer.id}:${new Date().toISOString().slice(0, 10)}`;
    await appendEvent(tx, scope, customer.id, eventType, "mini_program", "customer_touch", eventKey);
    return customer;
  }
  async function touchMiniProgramCustomer(scope, input = {}) { return db.transaction(tx => findOrCreateCustomer(tx, scope, { ...input, source: "mini_program", firstSeen: true })); }
  async function list(scope, query = {}) {
    const page = Math.max(1, Number(query.page) || 1); const pageSize = Math.min(100, Math.max(1, Number(query.pageSize) || 25)); const values = [...scopeValues(scope)];
    const where = ["c.tenant_id=$1", "c.workspace_id=$2", "c.store_id=$3"]; const q = String(query.q || "").trim().slice(0, 80);
    if (q) { values.push("%" + q + "%"); where.push("(coalesce(c.display_name,c.name,'') ilike $" + values.length + " or coalesce(c.phone,'') ilike $" + values.length + " or c.id::text ilike $" + values.length + ")"); }
    if (query.source) { values.push(String(query.source)); where.push("c.source=$" + values.length); }
    if (query.identity === "member") where.push("exists(select 1 from customer_memberships im where im.customer_id=c.id and im.tenant_id=c.tenant_id and im.workspace_id=c.workspace_id and im.store_id=c.store_id and im.status='active')");
    if (query.identity === "customer") where.push("c.order_count>0");
    if (query.levelId) { values.push(String(query.levelId)); where.push("exists(select 1 from customer_memberships lm where lm.customer_id=c.id and lm.level_id=$" + values.length + " and lm.tenant_id=c.tenant_id and lm.workspace_id=c.workspace_id and lm.store_id=c.store_id and lm.status='active')"); }
    if (query.tagId) { values.push(String(query.tagId)); where.push("exists(select 1 from customer_tag_links tl where tl.customer_id=c.id and tl.tag_id=$" + values.length + " and tl.tenant_id=c.tenant_id and tl.workspace_id=c.workspace_id and tl.store_id=c.store_id)"); }
    const count = await db.query("select count(*)::int count from customers c where " + where.join(" and "), values);
    values.push((page - 1) * pageSize, pageSize);
    const offsetIndex = values.length - 1;
    const limitIndex = values.length;
    const sort = ({ newest: "c.created_at desc", spend: "c.total_spend_fen desc,c.created_at desc", orders: "c.order_count desc,c.created_at desc", activity: "c.last_seen_at desc nulls last,c.created_at desc" })[String(query.sort || "activity")] || "c.last_seen_at desc nulls last,c.created_at desc";
    const rows = (await db.query("select c.id,coalesce(c.display_name,c.name) display_name,c.phone,c.source,c.created_at,c.last_seen_at,c.order_count,c.total_spend_fen,c.appointment_count, exists(select 1 from customer_memberships m where m.customer_id=c.id and m.tenant_id=c.tenant_id and m.workspace_id=c.workspace_id and m.store_id=c.store_id and m.status='active') is_member from customers c where " + where.join(" and ") + " order by " + sort + " offset $" + offsetIndex + " limit $" + limitIndex, values)).rows;
    return { items: rows.map(row => ({ id: row.id, name: row.display_name || anonymousName(row.id), phoneMasked: maskPhone(row.phone), source: row.source, isMember: row.is_member, orderCount: Number(row.order_count), totalSpendFen: Number(row.total_spend_fen), appointmentCount: Number(row.appointment_count), createdAt: row.created_at, lastSeenAt: row.last_seen_at })), page, pageSize, total: Number(count.rows[0] && count.rows[0].count || 0) };
  }
  async function stats(scope){const row=(await db.query("select count(*)::int total,count(*) filter(where order_count>0)::int customers,count(*) filter(where created_at>=now()-interval '30 days')::int new_30_days from customers where tenant_id=$1 and workspace_id=$2 and store_id=$3",scopeValues(scope))).rows[0];const members=(await db.query("select count(*)::int count from customer_memberships where tenant_id=$1 and workspace_id=$2 and store_id=$3 and status='active'",scopeValues(scope))).rows[0];return {total:Number(row?.total||0),customers:Number(row?.customers||0),members:Number(members?.count||0),new30Days:Number(row?.new_30_days||0)};}
  async function get(scope, id) {
    const row = (await db.query("select * from customers where id=$1 and tenant_id=$2 and workspace_id=$3 and store_id=$4", [id, ...scopeValues(scope)])).rows[0];
    if (!row) throw Object.assign(new Error("客户不存在"), { status: 404, code: "CUSTOMER_NOT_FOUND" });
    const related = await Promise.all([
      db.query("select id,appointment_number,start_at,service_name_snapshot,advisor_name_snapshot,status from appointments where customer_id=$1 and tenant_id=$2 and workspace_id=$3 and store_id=$4 order by start_at desc", [id,...scopeValues(scope)]),
      db.query("select id,order_no,status,payment_status,amount_fen,created_at from orders where customer_id=$1 and tenant_id=$2 and workspace_id=$3 and store_id=$4 order by created_at desc", [id,...scopeValues(scope)]),
      db.query("select event_type,source,resource_type,resource_id,occurred_at from customer_events where customer_id=$1 and tenant_id=$2 and workspace_id=$3 and store_id=$4 order by occurred_at desc limit 200", [id,...scopeValues(scope)]),
      db.query("select t.id,t.name from customer_tags t join customer_tag_links l on l.tag_id=t.id and l.customer_id=$1 and l.tenant_id=$2 and l.workspace_id=$3 and l.store_id=$4", [id,...scopeValues(scope)]),
      db.query("select id,author_user_id,content,created_at from customer_notes where customer_id=$1 and tenant_id=$2 and workspace_id=$3 and store_id=$4 order by created_at desc", [id,...scopeValues(scope)]),
      db.query("select m.status,m.joined_at,m.updated_at,l.id level_id,l.name level_name,l.level_order from customer_memberships m join membership_levels l on l.id=m.level_id where m.customer_id=$1 and m.tenant_id=$2 and m.workspace_id=$3 and m.store_id=$4", [id,...scopeValues(scope)]),
      db.query("select balance from customer_points_accounts where customer_id=$1 and tenant_id=$2 and workspace_id=$3 and store_id=$4", [id,...scopeValues(scope)])
    ]);
    const appointments = related[0].rows.map(item => ({ id:item.id,number:item.appointment_number,startAt:item.start_at,serviceName:item.service_name_snapshot,advisorName:item.advisor_name_snapshot,status:item.status,statusLabel:({pending:"待确认",confirmed:"已确认",completed:"已完成",cancelled:"已取消",no_show:"未到店"})[item.status]||item.status }));
    const orders = related[1].rows.map(item => ({ id:item.id,orderNo:item.order_no,status:item.status,paymentStatus:item.payment_status,amountFen:Number(item.amount_fen),createdAt:item.created_at }));
    const events = related[2].rows.map(item => ({ type:item.event_type,source:item.source,resourceType:item.resource_type,resourceId:item.resource_id,occurredAt:item.occurred_at }));
    const notes = related[4].rows.map(item => ({ id:item.id,authorUserId:item.author_user_id,content:item.content,createdAt:item.created_at }));
    return { id: row.id, name: row.display_name || row.name || anonymousName(row.id), source: row.source, createdAt: row.created_at, firstSeenAt: row.first_seen_at, lastSeenAt: row.last_seen_at, orderCount: Number(row.order_count), totalSpendFen: Number(row.total_spend_fen), appointmentCount: Number(row.appointment_count), phoneMasked: maskPhone(row.phone), tags: related[3].rows, notes, events, orders, appointments, membership: related[5].rows[0] || null, points: Number(related[6].rows[0] && related[6].rows[0].balance || 0) };
  }
  async function related(scope,id,kind){ const allowed={orders:"select id,order_no,status,payment_status,amount_fen,created_at from orders",appointments:"select id,appointment_number,start_at,service_name_snapshot,advisor_name_snapshot,status from appointments",events:"select event_type,source,resource_type,resource_id,occurred_at from customer_events"}; if(!allowed[kind])throw Object.assign(new Error("关联数据类型无效"),{status:400,code:"RELATED_TYPE_INVALID"}); const exists=(await db.query("select id from customers where id=$1 and tenant_id=$2 and workspace_id=$3 and store_id=$4",[id,...scopeValues(scope)])).rows[0];if(!exists)throw Object.assign(new Error("客户不存在"),{status:404,code:"CUSTOMER_NOT_FOUND"});const time=kind==="orders"?"created_at":kind==="appointments"?"start_at":"occurred_at";return (await db.query(`${allowed[kind]} where customer_id=$1 and tenant_id=$2 and workspace_id=$3 and store_id=$4 order by ${time} desc limit 200`,[id,...scopeValues(scope)])).rows; }
  async function get360(scope, customerId) {
    const customer = await get(scope, customerId);
    const points = await pointsLedger(scope, customerId);
    const timeline = [...(customer.events || [])].sort((a, b) => new Date(b.occurredAt) - new Date(a.occurredAt));
    return {
      ...customer,
      customer,
      summary: {
        appointmentCount: customer.appointmentCount,
        orderCount: customer.orderCount,
        membershipStatus: customer.membership?.status || null,
        pointsBalance: points.balance,
        lastActivityAt: timeline[0]?.occurredAt || customer.lastSeenAt || null
      },
      timeline,
      appointments: customer.appointments || [],
      orders: customer.orders || [],
      membership: customer.membership || null,
      points
    };
  }
  async function addNote(scope, id, input) {
    const content = String(input.content || "").trim(); if (!content) throw Object.assign(new Error("备注不能为空"), { status: 400, code: "NOTE_INVALID" });
    return db.transaction(async tx => { const exists = (await tx.query("select id from customers where id=$1 and tenant_id=$2 and workspace_id=$3 and store_id=$4", [id,...scopeValues(scope)])).rows[0]; if (!exists) throw Object.assign(new Error("客户不存在"), { status: 404, code: "CUSTOMER_NOT_FOUND" }); const row = (await tx.query("insert into customer_notes(id,tenant_id,workspace_id,store_id,customer_id,author_user_id,content) values($1,$2,$3,$4,$5,$6,$7) returning *", [uuid(),...scopeValues(scope),id,scope.userId || null,content.slice(0,5000)])).rows[0]; await appendEvent(tx,scope,id,"profile_updated","merchant","customer_note",row.id); await tx.query("insert into audit_events(id,tenant_id,workspace_id,actor_type,actor_id,action,resource_type,resource_id,request_id,metadata) values($1,$2,$3,'merchant',$4,'customer.note.create','customer_note',$5,$6,$7::jsonb)", [uuid(), scope.tenantId, scope.workspaceId, scope.userId || 'merchant', row.id, scope.requestId || uuid(), JSON.stringify({ customerId: id })]); return row; });
  }
  async function listTags(scope) { return tagRepository ? tagRepository.listTags(scope) : (await db.query("select id,name,created_at from customer_tags where tenant_id=$1 and workspace_id=$2 and store_id=$3 order by name", scopeValues(scope))).rows; }
  async function createTag(scope, input = {}) {
    if (tagRepository) return tagRepository.createTag(scope, input);
    const name = String(input.name || "").trim().slice(0, 80); if (!name) throw Object.assign(new Error("标签名称不能为空"), { status: 400, code: "TAG_INVALID" });
    return db.transaction(async tx => { const row = (await tx.query("insert into customer_tags(id,tenant_id,workspace_id,store_id,name) values($1,$2,$3,$4,$5) on conflict do nothing returning id,name,created_at", [uuid(), ...scopeValues(scope), name])).rows[0]; if (!row) throw Object.assign(new Error("标签已存在"), { status: 409, code: "TAG_EXISTS" }); await tx.query("insert into audit_events(id,tenant_id,workspace_id,actor_type,actor_id,action,resource_type,resource_id,request_id,metadata) values($1,$2,$3,'merchant',$4,'customer.tag.create','customer_tag',$5,$6,'{}'::jsonb)", [uuid(),scope.tenantId,scope.workspaceId,scope.userId || 'merchant',row.id,scope.requestId || uuid()]); return row; });
  }
  async function linkTag(scope, customerId, tagId) {
    return db.transaction(async tx => { const customer = (await tx.query("select id from customers where id=$1 and tenant_id=$2 and workspace_id=$3 and store_id=$4", [customerId,...scopeValues(scope)])).rows[0]; const tag = (await tx.query("select id,name from customer_tags where id=$1 and tenant_id=$2 and workspace_id=$3 and store_id=$4", [tagId,...scopeValues(scope)])).rows[0]; if (!customer || !tag) throw Object.assign(new Error("客户或标签不存在"), { status: 404, code: "CUSTOMER_NOT_FOUND" }); await tx.query("insert into customer_tag_links(tenant_id,workspace_id,store_id,customer_id,tag_id) values($1,$2,$3,$4,$5) on conflict do nothing", [...scopeValues(scope),customerId,tagId]); await tx.query("insert into audit_events(id,tenant_id,workspace_id,actor_type,actor_id,action,resource_type,resource_id,request_id,metadata) values($1,$2,$3,'merchant',$4,'customer.tag.link','customer_tag',$5,$6,'{}'::jsonb)", [uuid(),scope.tenantId,scope.workspaceId,scope.userId || 'merchant',tagId,scope.requestId || uuid()]); return tag; });
  }
  async function unlinkTag(scope, customerId, tagId) { return db.transaction(async tx=>{const result = await tx.query("delete from customer_tag_links where tenant_id=$1 and workspace_id=$2 and store_id=$3 and customer_id=$4 and tag_id=$5 returning tag_id", [...scopeValues(scope),customerId,tagId]); if (!result.rows[0]) throw Object.assign(new Error("标签绑定不存在"), { status: 404, code: "TAG_LINK_NOT_FOUND" });await audit(tx,scope,"customer.tag.unlink","customer_tag",tagId,{customerId});return { customerId, tagId, deleted: true };}); }
  async function membership(scope, customerId) { const row = (await db.query("select m.id,m.status,m.joined_at,m.updated_at,l.id level_id,l.name level_name,l.level_order,l.growth_threshold from customer_memberships m join membership_levels l on l.id=m.level_id where m.customer_id=$1 and m.tenant_id=$2 and m.workspace_id=$3 and m.store_id=$4", [customerId,...scopeValues(scope)])).rows[0]; return row || null; }
  async function joinMembership(scope, customerId, levelId = null) {
    return db.transaction(async tx => { const customer = (await tx.query("select id from customers where id=$1 and tenant_id=$2 and workspace_id=$3 and store_id=$4", [customerId,...scopeValues(scope)])).rows[0]; if (!customer) throw Object.assign(new Error("客户不存在"), { status: 404, code: "CUSTOMER_NOT_FOUND" }); const level = (await tx.query("select id from membership_levels where tenant_id=$1 and workspace_id=$2 and store_id=$3 and enabled=true and ($4::uuid is null or id=$4) order by level_order limit 1", [...scopeValues(scope),levelId || null])).rows[0]; if (!level) throw Object.assign(new Error("会员等级不存在"), { status: 400, code: "MEMBERSHIP_LEVEL_INVALID" }); let row=(await tx.query("select * from customer_memberships where tenant_id=$1 and workspace_id=$2 and store_id=$3 and customer_id=$4 and status='active' for update", [...scopeValues(scope),customerId])).rows[0]; if(row) row=(await tx.query("update customer_memberships set level_id=$1,updated_at=now() where id=$2 returning *",[level.id,row.id])).rows[0]; else row=(await tx.query("insert into customer_memberships(id,tenant_id,workspace_id,store_id,customer_id,level_id,status) values($1,$2,$3,$4,$5,$6,'active') returning *", [uuid(),...scopeValues(scope),customerId,level.id])).rows[0]; await appendEvent(tx,scope,customerId,"member_joined","merchant","customer_membership",row.id); await tx.query("insert into audit_events(id,tenant_id,workspace_id,actor_type,actor_id,action,resource_type,resource_id,request_id,metadata) values($1,$2,$3,'merchant',$4,'customer.membership.join','customer_membership',$5,$6,'{}'::jsonb)", [uuid(),scope.tenantId,scope.workspaceId,scope.userId || 'merchant',row.id,scope.requestId || uuid()]); return (await tx.query("select m.id,m.status,m.joined_at,m.updated_at,l.id level_id,l.name level_name,l.level_order,l.growth_threshold from customer_memberships m join membership_levels l on l.id=m.level_id where m.id=$1",[row.id])).rows[0]; });
  }
  async function adjustMembership(scope, customerId, levelId) {
    return db.transaction(async tx => { const row = (await tx.query("update customer_memberships m set level_id=$1,updated_at=now() from membership_levels l where m.id=(select id from customer_memberships where customer_id=$2 and tenant_id=$3 and workspace_id=$4 and store_id=$5 and status='active') and l.id=$1 and l.tenant_id=$3 and l.workspace_id=$4 and l.store_id=$5 returning m.*", [levelId,customerId,...scopeValues(scope)])).rows[0]; if (!row) throw Object.assign(new Error("会员或等级不存在"), { status: 404, code: "MEMBERSHIP_NOT_FOUND" }); await appendEvent(tx,scope,customerId,"member_level_changed","merchant","customer_membership",row.id); await tx.query("insert into audit_events(id,tenant_id,workspace_id,actor_type,actor_id,action,resource_type,resource_id,request_id,metadata) values($1,$2,$3,'merchant',$4,'customer.membership.level.update','customer_membership',$5,$6,'{}'::jsonb)",[uuid(),scope.tenantId,scope.workspaceId,scope.userId||'merchant',row.id,scope.requestId||uuid()]); return (await tx.query("select m.id,m.status,m.joined_at,m.updated_at,l.id level_id,l.name level_name,l.level_order,l.growth_threshold from customer_memberships m join membership_levels l on l.id=m.level_id where m.id=$1",[row.id])).rows[0]; });
  }
  async function levels(scope) { return (await db.query("select id,name,level_order,growth_threshold,enabled,benefits from membership_levels where tenant_id=$1 and workspace_id=$2 and store_id=$3 order by level_order", scopeValues(scope))).rows; }
  async function program(scope) { return (await db.query("select id,enabled,points_enabled,created_at,updated_at from membership_programs where tenant_id=$1 and workspace_id=$2 and store_id=$3",scopeValues(scope))).rows[0] || null; }
  async function updateProgram(scope,input={}) { return db.transaction(async tx=>{const row=(await tx.query("update membership_programs set enabled=$1,points_enabled=$2,updated_at=now() where tenant_id=$3 and workspace_id=$4 and store_id=$5 returning id,enabled,points_enabled,updated_at",[input.enabled===true,input.pointsEnabled===true,...scopeValues(scope)])).rows[0];if(!row)throw Object.assign(new Error("会员计划不存在"),{status:404,code:"MEMBERSHIP_PROGRAM_NOT_FOUND"});await audit(tx,scope,"customer.membership_program.update","membership_program",row.id,{enabled:row.enabled,pointsEnabled:row.points_enabled});return row;}); }
  async function saveLevel(scope,input={},id=null){const name=String(input.name||"").trim().slice(0,80);const order=Number(input.levelOrder);const threshold=Number(input.growthThreshold||0);if(!name||!Number.isInteger(order)||order<1||!Number.isSafeInteger(threshold)||threshold<0)throw Object.assign(new Error("会员等级设置无效"),{status:400,code:"MEMBERSHIP_LEVEL_INVALID"});const benefits=JSON.stringify(input.benefits||{});return db.transaction(async tx=>{let row;if(id){row=(await tx.query("update membership_levels set name=$1,level_order=$2,growth_threshold=$3,enabled=$4,benefits=$5::jsonb,updated_at=now() where id=$6 and tenant_id=$7 and workspace_id=$8 and store_id=$9 returning *",[name,order,threshold,input.enabled!==false,benefits,id,...scopeValues(scope)])).rows[0];if(!row)throw Object.assign(new Error("会员等级不存在"),{status:404,code:"MEMBERSHIP_LEVEL_NOT_FOUND"});}else row=(await tx.query("insert into membership_levels(id,tenant_id,workspace_id,store_id,name,level_order,growth_threshold,enabled,benefits) values($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb) returning *",[uuid(),...scopeValues(scope),name,order,threshold,input.enabled!==false,benefits])).rows[0];await audit(tx,scope,id?"customer.membership_level.update":"customer.membership_level.create","membership_level",row.id,{enabled:row.enabled});return row;});}
  async function pointsLedger(scope, customerId) { const account=(await db.query("select balance from customer_points_accounts where tenant_id=$1 and workspace_id=$2 and store_id=$3 and customer_id=$4", [...scopeValues(scope),customerId])).rows[0]; const ledger=(await db.query("select type,points,balance_after,reason,source_type,source_id,created_at from customer_points_ledger where tenant_id=$1 and workspace_id=$2 and store_id=$3 and customer_id=$4 order by created_at desc limit 200", [...scopeValues(scope),customerId])).rows; return { balance: Number(account?.balance || 0), ledger }; }
  async function points(scope, customerId) { return pointsLedger(scope, customerId); }
  async function adjustPoints(scope, id, input) {
    const delta = Number(input.points); if (!Number.isInteger(delta) || delta === 0 || Math.abs(delta) > 1000000) throw Object.assign(new Error("积分数量无效"), { status: 400, code: "POINTS_INVALID" });
    const key = String(input.idempotencyKey || "").trim(); if (!key) throw Object.assign(new Error("缺少幂等键"), { status: 400, code: "IDEMPOTENCY_REQUIRED" });
    return db.transaction(async tx => { const customer = (await tx.query("select id from customers where id=$1 and tenant_id=$2 and workspace_id=$3 and store_id=$4", [id,...scopeValues(scope)])).rows[0]; if (!customer) throw Object.assign(new Error("客户不存在"), { status: 404, code: "CUSTOMER_NOT_FOUND" }); await tx.query("insert into customer_points_accounts(tenant_id,workspace_id,store_id,customer_id) values($1,$2,$3,$4) on conflict do nothing", [...scopeValues(scope),id]); const account=(await tx.query("select balance from customer_points_accounts where tenant_id=$1 and workspace_id=$2 and store_id=$3 and customer_id=$4 for update", [...scopeValues(scope),id])).rows[0]; const balance=Number(account.balance)+delta; if(balance<0) throw Object.assign(new Error("积分余额不足"), { status: 409, code: "POINTS_INSUFFICIENT" }); const inserted=await tx.query("insert into customer_points_ledger(tenant_id,workspace_id,store_id,customer_id,type,points,balance_after,reason,source_type,source_id,operator_id,idempotency_key) values($1,$2,$3,$4,'adjust',$5,$6,$7,'merchant',null,$8,$9) on conflict(tenant_id,workspace_id,store_id,idempotency_key) do nothing returning *", [...scopeValues(scope),id,delta,balance,String(input.reason||"人工调整").slice(0,200),scope.userId||null,key]); if(!inserted.rows[0]) return { duplicate: true, balance: Number(account.balance) }; await tx.query("update customer_points_accounts set balance=$1,updated_at=now() where tenant_id=$2 and workspace_id=$3 and store_id=$4 and customer_id=$5", [balance,...scopeValues(scope),id]); await appendEvent(tx,scope,id,delta>0?"points_earned":"points_spent","merchant","customer_points_ledger",inserted.rows[0].id); await tx.query("insert into audit_events(id,tenant_id,workspace_id,actor_type,actor_id,action,resource_type,resource_id,request_id,metadata) values($1,$2,$3,'merchant',$4,'customer.points.adjust','customer_points_ledger',$5,$6,$7::jsonb)",[uuid(),scope.tenantId,scope.workspaceId,scope.userId||'merchant',inserted.rows[0].id,scope.requestId||uuid(),JSON.stringify({customerId:id,points:delta})]); return { duplicate:false,balance }; });
  }
  return { hashOpenId, findOrCreateCustomer, touchMiniProgramCustomer, appendEvent, ensureDefaults, list, stats, get, get360, related, addNote, adjustPoints, listTags, createTag, linkTag, unlinkTag, membership, joinMembership, adjustMembership, program, updateProgram, levels, saveLevel, points, pointsLedger, maskPhone };
}
module.exports = { createCustomerService, maskPhone, anonymousName };
