/**
 * 同步引擎 — 读取 config.json，自动生成/更新小程序源码
 * @param {object} cfg - 配置对象
 * @param {string} root - 小程序项目根目录
 * @returns {{ files: string[] }}
 */
function sync(cfg, root) {
  const fs = require("fs");
  const path = require("path");
  const updated = [];

  // ---- 1. mock.js ----
  const mockPath = path.join(root, "utils", "mock.js");
  const mockContent = `// 由管理面板自动生成 —— 请勿手动编辑
const categories = ${JSON.stringify(cfg.categories, null, 2)};

const products = ${JSON.stringify(cfg.products, null, 2)};

const heroes = ${JSON.stringify(cfg.heroes.map(h => ({ img: h.img, title: h.title, sub: h.sub, channel: h.channel })), null, 2)};

const memberBenefits = ${JSON.stringify(cfg.memberBenefits, null, 2)};

module.exports = { categories, products, heroes, memberBenefits };
`;
  fs.writeFileSync(mockPath, mockContent, "utf-8");
  updated.push("utils/mock.js");

  const serviceConfigPath = path.join(root, "utils", "service-config.js");
  const serviceBot = normalizeServiceBot(cfg.serviceBot);
  fs.writeFileSync(serviceConfigPath, `// Generated by PRIVLAN Commerce Studio.\nmodule.exports = ${JSON.stringify(serviceBot, null, 2)};\n`, "utf-8");
  updated.push("utils/service-config.js");

  // ---- 2. app.wxss (主题配色) ----
  const wxssPath = path.join(root, "app.wxss");
  const c = cfg.theme.colors;
  const wxssContent = `/* 全局样式 —— 由管理面板自动生成 */
page {
  background: ${c.bgPrimary};
  color: ${c.textPrimary};
  font-family: -apple-system, "PingFang SC", "Helvetica Neue", "Microsoft YaHei", sans-serif;
  font-size: 28rpx;
  line-height: 1.6;
}

.serif {
  font-family: Georgia, "Times New Roman", "Songti SC", serif;
  letter-spacing: 4rpx;
}

.btn-black {
  background: ${c.accent};
  color: ${c.bgPrimary};
  font-size: 28rpx;
  letter-spacing: 6rpx;
  border-radius: 0;
  padding: 0 80rpx;
  height: 96rpx;
  line-height: 96rpx;
  text-align: center;
}

.btn-outline {
  border: 1rpx solid ${c.accent};
  color: ${c.accent};
  font-size: 26rpx;
  letter-spacing: 4rpx;
  padding: 14rpx 60rpx;
  display: inline-block;
}

.hairline {
  height: 1rpx;
  background: ${c.border};
}

.section-title {
  font-size: 32rpx;
  letter-spacing: 8rpx;
  text-align: center;
  padding: 48rpx 0 32rpx;
  font-weight: 500;
  color: ${c.textPrimary};
}
`;
  fs.writeFileSync(wxssPath, wxssContent, "utf-8");
  updated.push("app.wxss");

  // ---- 3. app.json ----
  const appJsonPath = path.join(root, "app.json");
  const appJson = JSON.parse(fs.readFileSync(appJsonPath, "utf-8"));
  appJson.window.navigationBarBackgroundColor = c.bgPrimary;
  appJson.window.navigationBarTitleText = cfg.brand.name;
  appJson.window.navigationBarTextStyle = isDark(c.bgPrimary) ? "white" : "black";
  appJson.window.backgroundColor = c.bgPrimary;
  appJson.window.backgroundTextStyle = isDark(c.bgPrimary) ? "light" : "dark";
  appJson.tabBar.color = c.textSecondary;
  appJson.tabBar.selectedColor = c.accent;
  appJson.tabBar.backgroundColor = c.bgPrimary;
  appJson.pages = Array.isArray(appJson.pages) ? appJson.pages : [];
  ["pages/service-chat/index", "pages/appointment/index"].forEach(route => {
    if (!appJson.pages.includes(route)) appJson.pages.push(route);
  });
  // 更新 tabBar 文字
  const tabItems = getTabBarItems(cfg);
  appJson.tabBar.list.forEach((item, i) => {
    if (tabItems[i]) {
      item.text = tabItems[i].text;
    }
  });
  fs.writeFileSync(appJsonPath, JSON.stringify(appJson, null, 2), "utf-8");
  updated.push("app.json");

  const componentPages = ["home", "category", "campaign", "cart", "mine", "detail", "appointment"];
  for (const pageId of componentPages) {
    const pageJsonPath = path.join(root, "pages", pageId, `${pageId}.json`);
    if (!fs.existsSync(pageJsonPath)) continue;
    const pageConfig = JSON.parse(fs.readFileSync(pageJsonPath, "utf-8"));
    pageConfig.usingComponents = { ...(pageConfig.usingComponents || {}), "service-fab": "/components/service-fab/index" };
    fs.writeFileSync(pageJsonPath, JSON.stringify(pageConfig, null, 2) + "\n", "utf-8");
    updated.push(`pages/${pageId}/${pageId}.json`);
  }

  // ---- 4. custom-tab-bar/index.wxss ----
  const tabBarWxssPath = path.join(root, "custom-tab-bar", "index.wxss");
  const tabBar = cfg.tabBar || {};
  const parsedCenterSize = Number(tabBar.centerSize);
  const parsedCenterLift = Number(tabBar.centerLift);
  const centerSize = Math.min(140, Math.max(72, Number.isFinite(parsedCenterSize) ? parsedCenterSize : 96));
  const centerLift = Math.min(90, Math.max(0, Number.isFinite(parsedCenterLift) ? parsedCenterLift : 56));
  const tabBarWxss = `.tabbar {
  position: fixed;
  left: 0;
  right: 0;
  bottom: 0;
  height: 110rpx;
  padding-bottom: env(safe-area-inset-bottom);
  background: ${c.bgPrimary};
  border-top: 1rpx solid ${c.border};
  display: flex;
  align-items: stretch;
  z-index: 999;
}

.tab-item {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}

.tab-icon {
  width: 44rpx;
  height: 44rpx;
}

.tab-text {
  font-size: 20rpx;
  color: ${c.textSecondary};
  margin-top: 4rpx;
  letter-spacing: 2rpx;
}

.tab-text.on {
  color: ${c.accent};
}

.tab-center {
  position: relative;
}

.center-circle {
  width: ${centerSize}rpx;
  height: ${centerSize}rpx;
  border-radius: 50%;
  overflow: hidden;
  margin-top: -${centerLift}rpx;
  border: 6rpx solid ${c.bgPrimary};
  background: ${c.accent};
  box-shadow: 0 2rpx 12rpx ${hexToRgba(c.accent, 0.3)};
}

.center-img {
  width: 100%;
  height: 100%;
}
`;
  fs.writeFileSync(tabBarWxssPath, tabBarWxss, "utf-8");
  updated.push("custom-tab-bar/index.wxss");

  // ---- 5. custom-tab-bar/index.js (center text) ----
  const tabBarJsPath = path.join(root, "custom-tab-bar", "index.js");
  const tabBarJs = `Component({
  data: {
    selected: 0,
    list: ${JSON.stringify(generateTabBarList(cfg), null, 4)}
  },

  methods: {
    switchTab(e) {
      const { path, index } = e.currentTarget.dataset;
      this.setData({ selected: index });
      wx.switchTab({ url: path });
    }
  }
});
`;
  fs.writeFileSync(tabBarJsPath, tabBarJs, "utf-8");
  updated.push("custom-tab-bar/index.js");

  // ---- 6. 品牌名替换 (category.wxml, mine.wxml, cart.wxml) ----
  replaceInFile(path.join(root, "pages", "category", "category.wxml"), root, cfg);
  replaceInFile(path.join(root, "pages", "mine", "mine.wxml"), root, cfg);
  replaceInFile(path.join(root, "pages", "cart", "cart.wxml"), root, cfg);
  updated.push("pages/category/category.wxml", "pages/mine/mine.wxml", "pages/cart/cart.wxml");

  // ---- 7. 各页面 wxss 配色更新 ----
  updatePageStyles(root, cfg);
  updated.push("pages/*/*.wxss");

  // ---- 8. campaign 页面数据 ----
  const campaignJsPath = path.join(root, "pages", "campaign", "campaign.js");
  if (fs.existsSync(campaignJsPath)) {
    const campaignProducts = cfg.products.filter(p => cfg.campaign.productIds.includes(p.id));
    const campaignJs = generateCampaignJs(cfg, campaignProducts);
    fs.writeFileSync(campaignJsPath, campaignJs, "utf-8");
    updated.push("pages/campaign/campaign.js");
  }

  // ---- 9. campaign.wxml 时间条和标题 ----
  const campaignWxmlPath = path.join(root, "pages", "campaign", "campaign.wxml");
  if (fs.existsSync(campaignWxmlPath)) {
    let cwxml = fs.readFileSync(campaignWxmlPath, "utf-8");
    cwxml = cwxml.replace(/活动时间：[^<]*/g, cfg.campaign.timeBar);
    cwxml = cwxml.replace(/<view class="section-title serif">[^<]*<\/view>/, `<view class="section-title serif">${cfg.campaign.sectionTitle}</view>`);
    fs.writeFileSync(campaignWxmlPath, cwxml, "utf-8");
  }

  if (cfg.pageLayouts) {
    const syncPageLayout = require("./home-layout-sync");
    if (!Array.isArray(cfg.pageLayouts.appointment)) {
      cfg.pageLayouts.appointment = [
        { id: "appointment-hero", type: "appointment-hero", name: "预约页头图", enabled: true, props: { kicker: "PRIVLAN APPOINTMENT", title: "预约专属服务", description: "选择适合你的门店、时间和顾问，我们会提前做好准备。" }, style: { backgroundColor: "#171717", textColor: "#ffffff", paddingX: 24, paddingY: 28 }, visibility: { mobile: true, tablet: true, desktop: true } },
        { id: "appointment-form", type: "appointment-form", name: "预约表单", enabled: true, props: { showName: true, showPhone: true, showService: true, showStore: true, showDate: true, showTime: true, showAdvisor: true }, style: { backgroundColor: "#f4f3f0", textColor: "#171717", paddingX: 16, paddingY: 20 }, visibility: { mobile: true, tablet: true, desktop: true } },
        { id: "appointment-notes", type: "appointment-notes", name: "预约备注", enabled: true, props: { label: "到店备注", placeholder: "可填写想了解的款式、场合或其他需求" }, style: { backgroundColor: "#ffffff", textColor: "#171717", paddingX: 16, paddingY: 20 }, visibility: { mobile: true, tablet: true, desktop: true } },
        { id: "appointment-submit", type: "appointment-submit", name: "预约提交", enabled: true, props: { buttonText: "确认预约", successTitle: "预约已提交", successCopy: "我们会尽快确认你的预约，请留意顾问联系。" }, style: { backgroundColor: "#ffffff", textColor: "#171717", paddingX: 16, paddingY: 20 }, visibility: { mobile: true, tablet: true, desktop: true } }
      ];
    }
    const pageMeta = {
      home: { name: "首页" }, category: { name: "分类" }, campaign: { name: "系列活动" },
      cart: { name: "购物车" }, mine: { name: "我的" }, detail: { name: "商品详情" }, appointment: { name: "预约到店" }
    };
    const customRoutes = [];
    for (const page of (Array.isArray(cfg.customPages) ? cfg.customPages : [])) {
      if (!page || !/^custom-[a-z0-9-]+$/.test(page.id || "")) continue;
      const pageDir = path.join(root, "pages", page.id);
      fs.mkdirSync(pageDir, { recursive: true });
      const jsonPath = path.join(pageDir, `${page.id}.json`);
      fs.writeFileSync(jsonPath, JSON.stringify({ navigationStyle: "custom", usingComponents: { "service-fab": "/components/service-fab/index" } }, null, 2) + "\n", "utf-8");
      pageMeta[page.id] = { name: page.name || "自定义页面" };
      customRoutes.push(`pages/${page.id}/${page.id}`);
      updated.push(`pages/${page.id}/${page.id}.json`);
    }
    for (const [pageId, blocks] of Object.entries(cfg.pageLayouts)) {
      if (!Array.isArray(blocks) || !pageMeta[pageId]) continue;
      updated.push(...syncPageLayout(cfg, root, pageId, pageMeta[pageId]));
    }
    if (customRoutes.length) {
      const appJsonPath = path.join(root, "app.json");
      const appConfig = JSON.parse(fs.readFileSync(appJsonPath, "utf-8"));
      appConfig.pages = Array.isArray(appConfig.pages) ? appConfig.pages : [];
      for (const route of customRoutes) {
        if (!appConfig.pages.includes(route)) appConfig.pages.push(route);
      }
      fs.writeFileSync(appJsonPath, JSON.stringify(appConfig, null, 2) + "\n", "utf-8");
      updated.push("app.json");
    }
  }

  return { files: updated };
}

// ---- 辅助函数 ----

function isDark(hex) {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return (r * 299 + g * 587 + b * 114) / 1000 < 128;
}

function normalizeServiceBot(serviceBot = {}) {
  const defaults = [
    "我要预约", "你们的价格区间是多少？", "你们用的什么面料？",
    "版型与款式", "制作周期多久？", "转人工服务"
  ];
  return {
    enabled: serviceBot.enabled !== false,
    icon: serviceBot.icon || "/images/icon-headset.png",
    size: Math.max(64, Math.min(120, Number(serviceBot.size || 88))),
    right: Math.max(8, Math.min(300, Number(serviceBot.right || 24))),
    bottom: Math.max(112, Math.min(700, Number(serviceBot.bottom || 150))),
    welcomeMessage: String(serviceBot.welcomeMessage || "您好，我是 PRIVLAN 专属服务助手。请问今天想了解什么？").slice(0, 160),
    quickPrompts: (Array.isArray(serviceBot.quickPrompts) ? serviceBot.quickPrompts : defaults).map(value => String(value || "").trim()).filter(Boolean).slice(0, 8),
    answerProvider: "rules",
    humanServiceEnabled: serviceBot.humanServiceEnabled === true,
    authMode: serviceBot.authMode === "wechat" ? "wechat" : "test"
  };
}

function hexToRgba(hex, alpha) {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

function generateTabBarList(cfg) {
  const paths = [
    "/pages/home/home",
    "/pages/category/category",
    "/pages/campaign/campaign",
    "/pages/cart/cart",
    "/pages/mine/mine"
  ];
  const defaults = [
    { icon: "/images/tab-home.png", iconOn: "/images/tab-home-on.png" },
    { icon: "/images/tab-grid.png", iconOn: "/images/tab-grid-on.png" },
    { center: true, centerIcon: "/images/tab-center.png" },
    { icon: "/images/tab-bag.png", iconOn: "/images/tab-bag-on.png" },
    { icon: "/images/tab-user.png", iconOn: "/images/tab-user-on.png" }
  ];
  return getTabBarItems(cfg).map((item, i) => {
    const entry = { path: paths[i], text: item.text };
    if (item.center) {
      entry.center = true;
      entry.centerIcon = item.centerIcon || defaults[i].centerIcon;
    } else {
      entry.icon = item.icon || defaults[i].icon;
      entry.iconOn = item.iconOn || defaults[i].iconOn;
    }
    return entry;
  });
}

function getTabBarItems(cfg) {
  const defaults = [
    { text: "首页", icon: "/images/tab-home.png", iconOn: "/images/tab-home-on.png" },
    { text: "分类", icon: "/images/tab-grid.png", iconOn: "/images/tab-grid-on.png" },
    { text: "夏季系列", center: true, centerIcon: "/images/tab-center.png" },
    { text: "购物车", icon: "/images/tab-bag.png", iconOn: "/images/tab-bag-on.png" },
    { text: "我的", icon: "/images/tab-user.png", iconOn: "/images/tab-user-on.png" }
  ];
  const source = Array.isArray(cfg?.tabBar?.items) ? cfg.tabBar.items : [];
  return defaults.map((item, index) => ({ ...item, ...(source[index] || {}), center: index === 2 }));
}

function replaceInFile(filePath, root, cfg) {
  const fs = require("fs");
  if (!fs.existsSync(filePath)) return;
  let content = fs.readFileSync(filePath, "utf-8");
  // 替换品牌名（支持各种格式：LUXE, PRIVLAN, 或其他）
  content = content.replace(/成为\s+\S+\s+会员/g, `成为 ${cfg.brand.name} 会员`);
  content = content.replace(/添加\s+\S+\s+专属顾问/g, `添加 ${cfg.brand.name} 专属顾问`);
  // 替换会员 banner 中的品牌名
  content = content.replace(/class="member-brand serif">[^<]*</g, `class="member-brand serif">${cfg.brand.name}<`);
  // 替换 slogan
  if (cfg.brand.slogan) {
    content = content.replace(/成为\s+\S+\s+会员\s+享受更多礼遇服务/g, cfg.brand.slogan);
  }
  if (cfg.brand.advisorslogan) {
    content = content.replace(/扫描二维码，添加\s+\S+\s+专属顾问[^<]*/g, cfg.brand.advisorslogan);
  }
  fs.writeFileSync(filePath, content, "utf-8");
}

function updatePageStyles(root, cfg) {
  const fs = require("fs");
  const path = require("path");
  const c = cfg.theme.colors;

  // 页面背景和文字色映射
  const colorReplacements = [
    // 背景色
    [/#0a0a0a/g, c.bgPrimary],
    [/#161616/g, c.bgSecondary],
    [/#1e1e1e/g, c.bgTertiary],
    // 文字色
    [/#f0f0f0/g, c.textPrimary],
    [/#8a8a8a/g, c.textSecondary],
    // 强调色
    [/#c9a97e/g, c.accent],
    // 边框
    [/#2a2a2a/g, c.border],
  ];

  const pageDirs = ["home", "category", "campaign", "cart", "mine", "detail"];
  for (const dir of pageDirs) {
    const wxssPath = path.join(root, "pages", dir, `${dir}.wxss`);
    if (!fs.existsSync(wxssPath)) continue;
    let content = fs.readFileSync(wxssPath, "utf-8");
    for (const [pattern, replacement] of colorReplacements) {
      content = content.replace(pattern, replacement);
    }
    fs.writeFileSync(wxssPath, content, "utf-8");
  }
}

function generateCampaignJs(cfg, campaignProducts) {
  return `// 由管理面板自动生成
const { services } = require("../../utils/mock");

Page({
  data: {
    services: [
      { icon: "/images/svc-truck.png", text: "免费配送" },
      { icon: "/images/svc-return.png", text: "退换货服务" },
      { icon: "/images/svc-card.png", text: "免息分期" }
    ],
    list: ${JSON.stringify(campaignProducts, null, 6)}
  },

  goDetail(e) {
    wx.navigateTo({ url: "/pages/detail/detail?id=" + e.currentTarget.dataset.id });
  },

  goBack() {
    wx.switchTab({ url: "/pages/home/home" });
  },

  consult() {
    wx.showToast({ title: "请长按二维码添加顾问", icon: "none" });
  }
});
`;
}

module.exports = sync;
