/**
 * 同步引擎 — 读取 config.json，自动生成/更新小程序源码
 * @param {object} cfg - 配置对象
 * @param {string} root - 小程序项目根目录
 * @returns {{ files: string[] }}
 */
function sync(cfg, root, options = {}) {
  const fs = require("fs");
  const path = require("path");
  const updated = [];

  cfg.designSystem ||= {};
  cfg.designSystem.blockDefaults ||= {};
  if ([undefined, 1.5, 1.55].includes(cfg.designSystem.blockDefaults.lineHeight)) cfg.designSystem.blockDefaults.lineHeight = 1.65;
  Object.values(cfg.pageLayouts || {}).forEach(blocks => {
    if (!Array.isArray(blocks)) return;
    blocks.forEach(block => {
      if (!block || !block.style || (Array.isArray(block.overrideKeys) && block.overrideKeys.includes("lineHeight"))) return;
      if ([undefined, 1.5, 1.55].includes(block.style.lineHeight)) block.style.lineHeight = 1.65;
    });
  });

  // ---- 1. mock.js ----
  const mockPath = path.join(root, "utils", "mock.js");
  const mockContent = `// 由管理面板自动生成 —— 请勿手动编辑
const categories = ${JSON.stringify(cfg.categories, null, 2)};

const products = ${JSON.stringify(cfg.products, null, 2)};

const heroes = ${JSON.stringify(cfg.heroes.map(h => ({ img: h.img, title: h.title, sub: h.sub, channel: h.channel })), null, 2)};

const memberBenefits = ${JSON.stringify(cfg.memberBenefits, null, 2)};

module.exports = { categories, products, heroes, memberBenefits };
`;
  fs.writeFileSync(mockPath, mockContent, "utf-8");
  updated.push("utils/mock.js");

  const serviceConfigPath = path.join(root, "utils", "service-config.js");
  const serviceBot = normalizeServiceBot(cfg.serviceBot);
  fs.writeFileSync(serviceConfigPath, `// Generated by 我的店铺 Commerce Studio.\nmodule.exports = ${JSON.stringify(serviceBot, null, 2)};\n`, "utf-8");
  updated.push("utils/service-config.js");
  const serviceQueryConfigPath = path.join(root, "cloudfunctions", "serviceQuery", "store-config.js");
  fs.writeFileSync(serviceQueryConfigPath, `// Generated by ATELIER OS during mini-program sync.\nmodule.exports = ${JSON.stringify({ faqs: serviceBot.faqs, knowledgeNotes: serviceBot.knowledgeNotes }, null, 2)};\n`, "utf-8");
  updated.push("cloudfunctions/serviceQuery/store-config.js");
  const appointmentRuntimePath = path.join(root, "utils", "appointment-runtime.js");
  fs.writeFileSync(appointmentRuntimePath, `// Generated by ATELIER OS during mini-program sync. Public identifiers only.\nmodule.exports = ${JSON.stringify({ publicStoreId: String(options.publicStoreId || "") }, null, 2)};\n`, "utf-8");
  updated.push("utils/appointment-runtime.js");

  // ---- 2. app.wxss (主题配色) ----
  const wxssPath = path.join(root, "app.wxss");
  const c = cfg.theme.colors;
  const typography = {
    caption: 22, meta: 24, body: 28, sectionTitle: 34, pageTitle: 42, heroTitle: 54,
    bodyLineHeight: 1.65, headingLineHeight: 1.3,
    ...(cfg.designSystem?.miniProgramTypography || {})
  };
  const wxssContent = `/* 全局样式 —— 由管理面板自动生成 */
page {
  background: ${c.bgPrimary};
  color: ${c.textPrimary};
  font-family: -apple-system, "PingFang SC", "Helvetica Neue", "Microsoft YaHei", sans-serif;
  font-size: ${typography.body}rpx;
  line-height: ${typography.bodyLineHeight};
}

.serif {
  font-family: Georgia, "Times New Roman", "Songti SC", serif;
  letter-spacing: 4rpx;
}

.btn-black {
  background: ${c.accent};
  color: ${c.bgPrimary};
  font-size: ${typography.body}rpx;
  letter-spacing: 6rpx;
  border-radius: 0;
  padding: 0 80rpx;
  height: 96rpx;
  line-height: 96rpx;
  text-align: center;
}

.btn-outline {
  border: 1rpx solid ${c.accent};
  color: ${c.accent};
  font-size: ${typography.body}rpx;
  letter-spacing: 4rpx;
  min-height: 88rpx;
  padding: 0 60rpx;
  display: inline-flex;
  align-items: center;
  justify-content: center;
}

.hairline {
  height: 1rpx;
  background: ${c.border};
}

.section-title {
  font-size: ${typography.sectionTitle}rpx;
  line-height: ${typography.headingLineHeight};
  letter-spacing: 0;
  text-align: center;
  padding: 48rpx 0 32rpx;
  font-weight: 500;
  color: ${c.textPrimary};
}
`;
  fs.writeFileSync(wxssPath, wxssContent, "utf-8");
  updated.push("app.wxss");

  // ---- 3. app.json ----
  const appJsonPath = path.join(root, "app.json");
  const appJson = JSON.parse(fs.readFileSync(appJsonPath, "utf-8"));
  appJson.window.navigationBarBackgroundColor = c.bgPrimary;
  appJson.window.navigationBarTitleText = cfg.brand.name;
  appJson.window.navigationBarTextStyle = isDark(c.bgPrimary) ? "white" : "black";
  appJson.window.backgroundColor = c.bgPrimary;
  appJson.window.backgroundTextStyle = isDark(c.bgPrimary) ? "light" : "dark";
  appJson.tabBar.color = c.textSecondary;
  appJson.tabBar.selectedColor = c.accent;
  appJson.tabBar.backgroundColor = c.bgPrimary;
  appJson.pages = Array.isArray(appJson.pages) ? appJson.pages : [];
  ["pages/service-chat/index", "pages/appointment/index", "pages/my-appointments/index", "pages/webview/webview"].forEach(route => {
    if (!appJson.pages.includes(route)) appJson.pages.push(route);
  });
  // Generate exactly the configured 2–5 visible items; the schema, generator
  // and custom tab bar all consume the same normalized list.
  const tabItems = getTabBarItems(cfg);
  appJson.tabBar.list = tabItems.map(item => ({ pagePath: pagePathForTab(item.page).replace(/^\//, ""), text: item.text }));
  fs.writeFileSync(appJsonPath, JSON.stringify(appJson, null, 2), "utf-8");
  updated.push("app.json");

  const webviewDir = path.join(root, "pages", "webview");
  fs.mkdirSync(webviewDir, { recursive: true });
  fs.writeFileSync(path.join(webviewDir, "webview.js"), `Page({
  data: { url: "", error: "", loading: true },
  onLoad(options = {}) {
    let decoded = "";
    try { decoded = decodeURIComponent(String(options.url || "")); } catch (error) {
      return this.setData({ loading: false, error: "链接格式无效" });
    }
    if (!/^https:\\/\\//i.test(decoded)) return this.setData({ loading: false, error: "仅支持安全的 HTTPS 链接" });
    this.setData({ url: decoded, error: "", loading: true });
  },
  onWebviewLoad() { this.setData({ loading: false }); },
  onWebviewError() { this.setData({ loading: false, error: "页面加载失败，请检查网络或微信业务域名配置" }); },
  goBack() { wx.navigateBack({ fail: () => wx.switchTab({ url: "/pages/home/home" }) }); }
});
`, "utf-8");
  fs.writeFileSync(path.join(webviewDir, "webview.wxml"), `<view class="webview-page">
  <web-view wx:if="{{url && !error}}" src="{{url}}" bindload="onWebviewLoad" binderror="onWebviewError"></web-view>
  <view wx:if="{{error}}" class="webview-error"><view class="webview-error-title">无法打开链接</view><view class="webview-error-copy">{{error}}</view><button bindtap="goBack">返回</button></view>
</view>\n`, "utf-8");
  fs.writeFileSync(path.join(webviewDir, "webview.wxss"), `.webview-page{min-height:100vh;background:#fff}.webview-error{padding:240rpx 48rpx 120rpx;text-align:center}.webview-error-title{font-size:38rpx;font-weight:600}.webview-error-copy{margin:24rpx 0 40rpx;color:#666;font-size:28rpx;line-height:1.65}.webview-error button{min-width:240rpx;min-height:88rpx;background:#111;color:#fff;font-size:28rpx}\n`, "utf-8");
  fs.writeFileSync(path.join(webviewDir, "webview.json"), JSON.stringify({ navigationBarTitleText: "网页", navigationStyle: "default" }, null, 2) + "\n", "utf-8");
  updated.push("pages/webview/webview.js", "pages/webview/webview.wxml", "pages/webview/webview.wxss", "pages/webview/webview.json");

  const componentPages = ["home", "category", "campaign", "cart", "mine", "detail", "appointment"];
  for (const pageId of componentPages) {
    const pageJsonPath = path.join(root, "pages", pageId, `${pageId}.json`);
    if (!fs.existsSync(pageJsonPath)) continue;
    const pageConfig = JSON.parse(fs.readFileSync(pageJsonPath, "utf-8"));
    pageConfig.usingComponents = { ...(pageConfig.usingComponents || {}), "service-fab": "/components/service-fab/index" };
    fs.writeFileSync(pageJsonPath, JSON.stringify(pageConfig, null, 2) + "\n", "utf-8");
    updated.push(`pages/${pageId}/${pageId}.json`);
  }

  // ---- 4. custom-tab-bar/index.wxss ----
  const tabBarWxssPath = path.join(root, "custom-tab-bar", "index.wxss");
  const tabBar = cfg.tabBar || {};
  const parsedCenterSize = Number(tabBar.centerSize);
  const parsedCenterLift = Number(tabBar.centerLift);
  const centerSize = Math.min(140, Math.max(72, Number.isFinite(parsedCenterSize) ? parsedCenterSize : 96));
  const centerLift = Math.min(90, Math.max(0, Number.isFinite(parsedCenterLift) ? parsedCenterLift : 56));
  const tabBarWxss = `.tabbar {
  position: fixed;
  left: 0;
  right: 0;
  bottom: 0;
  height: 110rpx;
  padding-bottom: env(safe-area-inset-bottom);
  background: ${c.bgPrimary};
  border-top: 1rpx solid ${c.border};
  display: flex;
  align-items: stretch;
  z-index: 999;
}

.tab-item {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}

.tab-icon {
  width: 44rpx;
  height: 44rpx;
}

.tab-text {
  font-size: 20rpx;
  color: ${c.textSecondary};
  margin-top: 4rpx;
  letter-spacing: 2rpx;
}

.tab-text.on {
  color: ${c.accent};
}

.tab-center {
  position: relative;
}

.center-circle {
  width: ${centerSize}rpx;
  height: ${centerSize}rpx;
  border-radius: 50%;
  overflow: hidden;
  margin-top: -${centerLift}rpx;
  border: 6rpx solid ${c.bgPrimary};
  background: ${c.accent};
  box-shadow: 0 2rpx 12rpx ${hexToRgba(c.accent, 0.3)};
}

.center-img {
  width: 100%;
  height: 100%;
}
`;
  fs.writeFileSync(tabBarWxssPath, tabBarWxss, "utf-8");
  updated.push("custom-tab-bar/index.wxss");

  // ---- 5. custom-tab-bar/index.js (center text) ----
  const tabBarJsPath = path.join(root, "custom-tab-bar", "index.js");
  const tabBarJs = `Component({
  data: {
    selected: 0,
    list: ${JSON.stringify(generateTabBarList(cfg), null, 4)}
  },

  methods: {
    switchTab(e) {
      const { path, index } = e.currentTarget.dataset;
      this.setData({ selected: index });
      wx.switchTab({ url: path });
    }
  }
});
`;
  fs.writeFileSync(tabBarJsPath, tabBarJs, "utf-8");
  updated.push("custom-tab-bar/index.js");

  // ---- 6. 品牌名替换 (category.wxml, mine.wxml, cart.wxml) ----
  replaceInFile(path.join(root, "pages", "category", "category.wxml"), root, cfg);
  replaceInFile(path.join(root, "pages", "mine", "mine.wxml"), root, cfg);
  replaceInFile(path.join(root, "pages", "cart", "cart.wxml"), root, cfg);
  updated.push("pages/category/category.wxml", "pages/mine/mine.wxml", "pages/cart/cart.wxml");

  // ---- 7. 各页面 wxss 配色更新 ----
  updatePageStyles(root, cfg);
  updated.push("pages/*/*.wxss");

  // ---- 8. campaign 页面数据 ----
  const campaignJsPath = path.join(root, "pages", "campaign", "campaign.js");
  if (fs.existsSync(campaignJsPath)) {
    const campaignProducts = cfg.products.filter(p => cfg.campaign.productIds.includes(p.id));
    const campaignJs = generateCampaignJs(cfg, campaignProducts);
    fs.writeFileSync(campaignJsPath, campaignJs, "utf-8");
    updated.push("pages/campaign/campaign.js");
  }

  // ---- 9. campaign.wxml 时间条和标题 ----
  const campaignWxmlPath = path.join(root, "pages", "campaign", "campaign.wxml");
  if (fs.existsSync(campaignWxmlPath)) {
    let cwxml = fs.readFileSync(campaignWxmlPath, "utf-8");
    cwxml = cwxml.replace(/活动时间：[^<]*/g, cfg.campaign.timeBar);
    cwxml = cwxml.replace(/<view class="section-title serif">[^<]*<\/view>/, `<view class="section-title serif">${cfg.campaign.sectionTitle}</view>`);
    fs.writeFileSync(campaignWxmlPath, cwxml, "utf-8");
  }

  if (cfg.pageLayouts) {
    const syncPageLayout = require("./home-layout-sync");
    if (!Array.isArray(cfg.pageLayouts.appointment)) {
      cfg.pageLayouts.appointment = [
        { id: "appointment-hero", type: "appointment-hero", name: "预约页头图", enabled: true, props: { kicker: "我的店铺 APPOINTMENT", title: "预约专属服务", description: "选择适合你的门店、时间和顾问，我们会提前做好准备。" }, style: { backgroundColor: "#171717", textColor: "#ffffff", paddingX: 24, paddingY: 28 }, visibility: { mobile: true, tablet: true, desktop: true } },
        { id: "appointment-form", type: "appointment-form", name: "预约表单", enabled: true, props: { showName: true, showPhone: true, showService: true, showStore: true, showDate: true, showTime: true, showAdvisor: true }, style: { backgroundColor: "#f4f3f0", textColor: "#171717", paddingX: 16, paddingY: 20 }, visibility: { mobile: true, tablet: true, desktop: true } },
        { id: "appointment-notes", type: "appointment-notes", name: "预约备注", enabled: true, props: { label: "到店备注", placeholder: "可填写想了解的款式、场合或其他需求" }, style: { backgroundColor: "#ffffff", textColor: "#171717", paddingX: 16, paddingY: 20 }, visibility: { mobile: true, tablet: true, desktop: true } },
        { id: "appointment-submit", type: "appointment-submit", name: "预约提交", enabled: true, props: { buttonText: "确认预约", successTitle: "预约已提交", successCopy: "我们会尽快确认你的预约，请留意顾问联系。" }, style: { backgroundColor: "#ffffff", textColor: "#171717", paddingX: 16, paddingY: 20 }, visibility: { mobile: true, tablet: true, desktop: true } }
      ];
    }
    const pageMeta = {
      home: { name: "首页" }, category: { name: "分类" }, campaign: { name: "系列活动" },
      cart: { name: "购物车" }, mine: { name: "我的" }, detail: { name: "商品详情" }, appointment: { name: "预约到店" }
    };
    const customRoutes = [];
    for (const page of (Array.isArray(cfg.customPages) ? cfg.customPages : [])) {
      if (!page || !/^custom-[a-z0-9-]+$/.test(page.id || "")) continue;
      const pageDir = path.join(root, "pages", page.id);
      fs.mkdirSync(pageDir, { recursive: true });
      const jsonPath = path.join(pageDir, `${page.id}.json`);
      fs.writeFileSync(jsonPath, JSON.stringify({ navigationStyle: "custom", usingComponents: { "service-fab": "/components/service-fab/index" } }, null, 2) + "\n", "utf-8");
      pageMeta[page.id] = { name: page.name || "自定义页面", path: page.path || `/pages/${page.id}/${page.id}`, shareTitle: page.shareTitle || page.name || cfg.brand.name, shareImage: page.shareImage || "", description: page.description || "" };
      customRoutes.push(`pages/${page.id}/${page.id}`);
      updated.push(`pages/${page.id}/${page.id}.json`);
    }
    const customPageRoot = path.join(root, "pages");
    if (fs.existsSync(customPageRoot)) {
      const activeCustomIds = new Set(customRoutes.map(route => route.split("/")[1]));
      for (const entry of fs.readdirSync(customPageRoot, { withFileTypes: true })) {
        if (!entry.isDirectory() || !entry.name.startsWith("custom-") || activeCustomIds.has(entry.name)) continue;
        fs.rmSync(path.join(customPageRoot, entry.name), { recursive: true, force: true });
        updated.push(`pages/${entry.name} (removed)`);
      }
    }
    for (const [pageId, blocks] of Object.entries(cfg.pageLayouts)) {
      if (!Array.isArray(blocks) || !pageMeta[pageId]) continue;
      updated.push(...syncPageLayout(cfg, root, pageId, pageMeta[pageId]));
    }
    const appJsonPath = path.join(root, "app.json");
    const appConfig = JSON.parse(fs.readFileSync(appJsonPath, "utf-8"));
    appConfig.pages = (Array.isArray(appConfig.pages) ? appConfig.pages : []).filter(route => !/^pages\/custom-[a-z0-9-]+\/custom-[a-z0-9-]+$/.test(route) || customRoutes.includes(route));
    for (const route of customRoutes) {
      if (!appConfig.pages.includes(route)) appConfig.pages.push(route);
    }
    fs.writeFileSync(appJsonPath, JSON.stringify(appConfig, null, 2) + "\n", "utf-8");
    updated.push("app.json");
  }

  return { files: updated };
}

// ---- 辅助函数 ----

function isDark(hex) {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return (r * 299 + g * 587 + b * 114) / 1000 < 128;
}

function normalizeServiceBot(serviceBot = {}) {
  const defaults = [
    "我要预约", "你们的价格区间是多少？", "你们用的什么面料？",
    "版型与款式", "制作周期多久？", "转人工服务"
  ];
  return {
    enabled: serviceBot.enabled !== false,
    icon: serviceBot.icon || "/images/icon-headset.png",
    size: Math.max(64, Math.min(120, Number(serviceBot.size || 88))),
    right: Math.max(8, Math.min(300, Number(serviceBot.right || 24))),
    bottom: Math.max(112, Math.min(700, Number(serviceBot.bottom || 150))),
    welcomeMessage: String(serviceBot.welcomeMessage || "您好，我是 我的店铺 专属服务助手。请问今天想了解什么？").slice(0, 160),
    quickPrompts: (Array.isArray(serviceBot.quickPrompts) ? serviceBot.quickPrompts : defaults).map(value => String(value || "").trim()).filter(Boolean).slice(0, 8),
    faqs: (Array.isArray(serviceBot.faqs) ? serviceBot.faqs : []).filter(item => item && item.enabled !== false && item.question && item.answer).map((item, index) => ({
      id: String(item.id || `faq-${index + 1}`), question: String(item.question).trim().slice(0, 80),
      keywords: (Array.isArray(item.keywords) ? item.keywords : []).map(value => String(value || "").trim()).filter(Boolean).slice(0, 12),
      answer: String(item.answer).trim().slice(0, 1200), showAsPrompt: item.showAsPrompt !== false
    })).slice(0, 100),
    knowledgeNotes: (Array.isArray(serviceBot.knowledgeNotes) ? serviceBot.knowledgeNotes : []).filter(item => item && item.title && item.content).map((item, index) => ({
      id: String(item.id || `note-${index + 1}`), title: String(item.title).trim().slice(0, 80), content: String(item.content).trim().slice(0, 20000)
    })).slice(0, 50),
    answerProvider: "rules",
    humanServiceEnabled: serviceBot.humanServiceEnabled === true,
    authMode: serviceBot.authMode === "wechat" ? "wechat" : "test"
  };
}

function hexToRgba(hex, alpha) {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

function generateTabBarList(cfg) {
  const featuredId = cfg?.tabBar?.featuredItemId || null;
  return getTabBarItems(cfg).map((item, i) => {
    const entry = { path: pagePathForTab(item.page), text: item.text };
    if (featuredId === item.id) { entry.center = true; entry.centerIcon = item.centerIcon || item.icon || "/images/tab-center.png"; }
    else { entry.icon = item.icon || "/images/tab-home.png"; entry.iconOn = item.iconOn || item.selectedIcon || item.icon || "/images/tab-home-on.png"; }
    return entry;
  });
}

function pagePathForTab(page) {
  const paths = { home: "/pages/home/home", category: "/pages/category/category", campaign: "/pages/campaign/campaign", cart: "/pages/cart/cart", mine: "/pages/mine/mine", appointment: "/pages/appointment/index", custom: "/pages/home/home" };
  return paths[String(page || "home")] || "/pages/home/home";
}

function getTabBarItems(cfg) {
  const source = Array.isArray(cfg?.tabBar?.items) ? cfg.tabBar.items : [];
  const fallback = [
    { id: "tab-1", text: "首页", page: "home", icon: "/images/tab-home.png", iconOn: "/images/tab-home-on.png" },
    { id: "tab-2", text: "分类", page: "category", icon: "/images/tab-grid.png", iconOn: "/images/tab-grid-on.png" },
    { id: "tab-3", text: "购物车", page: "cart", icon: "/images/tab-bag.png", iconOn: "/images/tab-bag-on.png" },
    { id: "tab-4", text: "我的", page: "mine", icon: "/images/tab-user.png", iconOn: "/images/tab-user-on.png" }
  ];
  const items = (source.length ? source : fallback).filter(item => item.visible !== false).sort((a,b) => Number(a.order || 0) - Number(b.order || 0)).slice(0, 5).map((item, index) => ({ ...item, id: String(item.id || `tab-${index + 1}`) }));
  if (items.length < 2) throw new Error("底部导航至少需要 2 个可见项");
  if (new Set(items.map(item => String(item.id))).size !== items.length) throw new Error("底部导航 ID 必须唯一");
  if (items.some(item => !pagePathForTab(item.page))) throw new Error("底部导航目标页面无效");
  return items;
}

function replaceInFile(filePath, root, cfg) {
  const fs = require("fs");
  if (!fs.existsSync(filePath)) return;
  let content = fs.readFileSync(filePath, "utf-8");
  // 替换品牌名（支持各种格式：LUXE, 我的店铺, 或其他）
  content = content.replace(/成为\s+\S+\s+会员/g, `成为 ${cfg.brand.name} 会员`);
  content = content.replace(/添加\s+\S+\s+服务顾问/g, `添加 ${cfg.brand.name} 服务顾问`);
  // 替换会员 banner 中的品牌名
  content = content.replace(/class="member-brand serif">[^<]*</g, `class="member-brand serif">${cfg.brand.name}<`);
  // 替换 slogan
  if (cfg.brand.slogan) {
    content = content.replace(/成为\s+\S+\s+会员\s+享受更多礼遇服务/g, cfg.brand.slogan);
  }
  if (cfg.brand.advisorslogan) {
    content = content.replace(/扫描二维码，添加\s+\S+\s+服务顾问[^<]*/g, cfg.brand.advisorslogan);
  }
  fs.writeFileSync(filePath, content, "utf-8");
}

function updatePageStyles(root, cfg) {
  const fs = require("fs");
  const path = require("path");
  const c = cfg.theme.colors;

  // 页面背景和文字色映射
  const colorReplacements = [
    // 背景色
    [/#0a0a0a/g, c.bgPrimary],
    [/#161616/g, c.bgSecondary],
    [/#1e1e1e/g, c.bgTertiary],
    // 文字色
    [/#f0f0f0/g, c.textPrimary],
    [/#8a8a8a/g, c.textSecondary],
    // 强调色
    [/#c9a97e/g, c.accent],
    // 边框
    [/#2a2a2a/g, c.border],
  ];

  const pageDirs = ["home", "category", "campaign", "cart", "mine", "detail"];
  for (const dir of pageDirs) {
    const wxssPath = path.join(root, "pages", dir, `${dir}.wxss`);
    if (!fs.existsSync(wxssPath)) continue;
    let content = fs.readFileSync(wxssPath, "utf-8");
    for (const [pattern, replacement] of colorReplacements) {
      content = content.replace(pattern, replacement);
    }
    fs.writeFileSync(wxssPath, content, "utf-8");
  }
}

function generateCampaignJs(cfg, campaignProducts) {
  return `// 由管理面板自动生成
const { services } = require("../../utils/mock");

Page({
  data: {
    services: [
      { icon: "/images/svc-truck.png", text: "免费配送" },
      { icon: "/images/svc-return.png", text: "退换货服务" },
      { icon: "/images/svc-card.png", text: "免息分期" }
    ],
    list: ${JSON.stringify(campaignProducts, null, 6)}
  },

  goDetail(e) {
    wx.navigateTo({ url: "/pages/detail/detail?id=" + e.currentTarget.dataset.id });
  },

  goBack() {
    wx.switchTab({ url: "/pages/home/home" });
  },

  consult() {
    wx.showToast({ title: "请长按二维码添加顾问", icon: "none" });
  }
});
`;
}

module.exports = sync;
module.exports.getTabBarItems = getTabBarItems;
module.exports.generateTabBarList = generateTabBarList;
