'use strict';
const crypto = require('node:crypto');
const { SupabaseAdapterError } = require('./meoo-supabase-adapter');
const id = () => crypto.randomUUID();
const vals = scope => { if (!scope?.tenantId || !scope.workspaceId || !scope.storeId) throw new SupabaseAdapterError('SCOPE_REQUIRED','tenant/workspace/store scope is required',400); return [scope.tenantId,scope.workspaceId,scope.storeId]; };
const enc = value => encodeURIComponent(String(value));
const qscope = (s, extra='') => { const [t,w,st]=vals(s); return `tenant_id=eq.${enc(t)}&workspace_id=eq.${enc(w)}&store_id=eq.${enc(st)}${extra ? `&${extra}` : ''}`; };
const wqscope = (s, extra='') => { const [t,w]=vals(s); return `tenant_id=eq.${enc(t)}&workspace_id=eq.${enc(w)}${extra ? `&${extra}` : ''}`; };
const first = body => Array.isArray(body) ? body[0] || null : body;
function mapError(error, fallback='database request failed') { if (error?.status) throw error; throw new SupabaseAdapterError('DATABASE_UNAVAILABLE',fallback,503); }
function createMeooLaunchV1Repository({ adapter } = {}) {
  if (!adapter || typeof adapter.readResource !== 'function' || typeof adapter.insertResource !== 'function' || typeof adapter.updateResource !== 'function') throw new TypeError('Meoo Launch V1 repository requires a resource adapter');
  const read = (table,s,extra='') => adapter.readResource(table, String(table).startsWith('workflow_') ? wqscope(s,extra) : qscope(s,extra));
  const insert = async (table,row) => first(await adapter.insertResource(table,row));
  const update = async (table,query,patch) => first(await adapter.updateResource(table,query,patch));
  const audit = async (s,action,resourceType,resourceId,metadata={}) => insert('audit_events',{id:id(),tenant_id:s.tenantId,workspace_id:s.workspaceId,actor_type:s.actorType||'merchant',actor_id:s.userId||'system',action,resource_type:resourceType,resource_id:resourceId,request_id:s.requestId||id(),metadata});
  const event = async (s,customerId,eventType,resourceType,resourceId,metadata={}) => insert('customer_events',{id:id(),tenant_id:s.tenantId,workspace_id:s.workspaceId,store_id:s.storeId,customer_id:customerId,event_type:eventType,source:'merchant',resource_type:resourceType,resource_id:resourceId,metadata});
  async function customerTagLink(s,customerId,tagId) {
    const customers=await read('customers',s,`id=eq.${enc(customerId)}&limit=1`); const tags=await read('customer_tags',s,`id=eq.${enc(tagId)}&limit=1`);
    if(!first(customers)||!first(tags)) throw Object.assign(new Error('客户或标签不存在'),{status:404,code:'CUSTOMER_NOT_FOUND'});
    await insert('customer_tag_links',{tenant_id:s.tenantId,workspace_id:s.workspaceId,store_id:s.storeId,customer_id:customerId,tag_id:tagId});
    await audit(s,'customer.tag.link','customer_tag',tagId,{customerId}); return first(tags);
  }
  async function membershipRule(s,input={}) {
    const levelId=String(input.levelId||''); if(!levelId) throw Object.assign(new Error('缺少等级'),{status:400,code:'MEMBERSHIP_RULE_INVALID'});
    const level=first(await read('membership_levels',s,`id=eq.${enc(levelId)}&limit=1`)); if(!level) throw Object.assign(new Error('会员等级不存在'),{status:404,code:'MEMBERSHIP_LEVEL_NOT_FOUND'});
    const existing=first(await read('membership_level_rules',s,`level_id=eq.${enc(levelId)}&limit=1`));
    const row={tenant_id:s.tenantId,workspace_id:s.workspaceId,store_id:s.storeId,level_id:levelId,spend_threshold_fen:input.spendThresholdFen==null?null:Number(input.spendThresholdFen),points_threshold:input.pointsThreshold==null?null:Number(input.pointsThreshold),appointment_count_threshold:input.appointmentCountThreshold==null?null:Number(input.appointmentCountThreshold),effective_from:input.effectiveFrom||new Date().toISOString(),manual_only:input.manualOnly===true,enabled:input.enabled!==false};
    const saved=existing ? await update('membership_level_rules',qscope(s,`level_id=eq.${enc(levelId)}`),row) : await insert('membership_level_rules',row); await audit(s,'customer.membership.rule.update','membership_level_rule',saved?.id||existing?.id,{levelId}); return saved||existing;
  }
  async function membershipActivity(s) {
    const [levels, programs, changes, memberships] = await Promise.all([read('membership_levels',s,'order=level_order.asc'), read('membership_programs',s,'limit=1'), read('customer_events',s,'event_type=eq.member_level_changed&order=occurred_at.desc&limit=50'), read('customer_memberships',s,'status=eq.active')]);
    const customerCounts = new Map(); for (const row of memberships) customerCounts.set(String(row.level_id), (customerCounts.get(String(row.level_id)) || 0) + 1);
    return { program: first(programs), levels, customerCounts: [...customerCounts.entries()].map(([level_id,count]) => ({ level_id, count })), recentChanges: changes };
  }
  async function membershipEvaluate(s,customerId) {
    const customer=first(await read('customers',s,`id=eq.${enc(customerId)}&limit=1`)); if(!customer) throw Object.assign(new Error('客户不存在'),{status:404,code:'CUSTOMER_NOT_FOUND'});
    const override=first(await read('membership_overrides',s,`customer_id=eq.${enc(customerId)}&or=(expires_at.is.null,expires_at.gt.${enc(new Date().toISOString())})&limit=1`));
    const accounts=first(await read('customer_points_accounts',s,`customer_id=eq.${enc(customerId)}&limit=1`)); const points=Number(accounts?.balance||0);
    const levels=await read('membership_levels',s,'enabled=eq.true&order=level_order.asc'); const rules=await read('membership_level_rules',s,'enabled=eq.true');
    const target=override ? ({...override,level_id:override.level_id}) : levels.map(level=>({level,...(rules.find(r=>String(r.level_id)===String(level.id))||{})})).filter(x=>(x.spend_threshold_fen==null||Number(customer.total_spend_fen||0)>=Number(x.spend_threshold_fen))&&(x.points_threshold==null||points>=Number(x.points_threshold))&&(x.appointment_count_threshold==null||Number(customer.appointment_count||0)>=Number(x.appointment_count_threshold))).pop() || levels[0];
    if(!target) throw Object.assign(new Error('没有可用会员等级'),{status:400,code:'MEMBERSHIP_LEVEL_INVALID'});
    const targetId=target.level_id||target.level?.id||target.id; const targetLevel=target.level||target; const current=first(await read('customer_memberships',s,`customer_id=eq.${enc(customerId)}&status=eq.active&limit=1`));
    if(current && String(current.level_id)===String(targetId)) return {changed:false,levelId:targetId,levelName:targetLevel.name,levelOrder:Number(targetLevel.level_order)};
    let membershipId=current?.id; if(current) { const row=await update('customer_memberships',qscope(s,`id=eq.${enc(current.id)}`),{level_id:targetId,updated_at:new Date().toISOString()}); membershipId=row?.id||current.id; }
    else { const row=await insert('customer_memberships',{id:id(),tenant_id:s.tenantId,workspace_id:s.workspaceId,store_id:s.storeId,customer_id:customerId,level_id:targetId,status:'active'}); membershipId=row.id; }
    const direction=current && Number(targetLevel.level_order)<Number((levels.find(l=>String(l.id)===String(current.level_id))||{}).level_order)?'downgrade':'upgrade';
    await event(s,customerId,'member_level_changed','customer_membership',membershipId,{direction,fromLevelId:current?.level_id||null,toLevelId:targetId,reason:override?'manual_override':'qualification'});
    await audit(s,'customer.membership.auto_evaluate','customer_membership',membershipId,{direction,toLevelId:targetId});
    return {changed:true,direction,levelId:targetId,levelName:targetLevel.name,levelOrder:Number(targetLevel.level_order),membershipId};
  }
  async function membershipOverride(s,customerId,input={}) { const levelId=String(input.levelId||''); if(!levelId||!String(input.reason||'').trim()) throw Object.assign(new Error('等级和原因不能为空'),{status:400,code:'MEMBERSHIP_OVERRIDE_INVALID'}); const level=first(await read('membership_levels',s,`id=eq.${enc(levelId)}&limit=1`)); if(!level) throw Object.assign(new Error('会员等级不存在'),{status:404,code:'MEMBERSHIP_LEVEL_NOT_FOUND'}); await insert('membership_overrides',{tenant_id:s.tenantId,workspace_id:s.workspaceId,store_id:s.storeId,customer_id:customerId,level_id:levelId,reason:String(input.reason).slice(0,500),expires_at:input.expiresAt||null,created_by:s.userId||'merchant'}); await audit(s,'customer.membership.override','customer_membership',customerId,{levelId}); return membershipEvaluate(s,customerId); }
  async function membershipRedeem(s,customerId,benefitKey,input={}) { const key=String(input.idempotencyKey||'').trim(); if(!key) throw Object.assign(new Error('缺少幂等键'),{status:400,code:'IDEMPOTENCY_REQUIRED'}); const m=first(await read('customer_memberships',s,`customer_id=eq.${enc(customerId)}&status=eq.active&limit=1`)); if(!m) throw Object.assign(new Error('客户尚未加入会员'),{status:409,code:'MEMBERSHIP_REQUIRED'}); const level=first(await read('membership_levels',s,`id=eq.${enc(m.level_id)}&limit=1`)); const benefits=level?.benefits||{}; if(!Object.prototype.hasOwnProperty.call(benefits,benefitKey)) throw Object.assign(new Error('当前等级不具备该权益'),{status:403,code:'BENEFIT_NOT_ELIGIBLE'}); const existing=first(await read('membership_redemptions',s,`idempotency_key=eq.${enc(key)}&limit=1`)); if(existing) return {duplicate:true}; const row=await insert('membership_redemptions',{id:id(),tenant_id:s.tenantId,workspace_id:s.workspaceId,store_id:s.storeId,customer_id:customerId,level_id:m.level_id,benefit_key:String(benefitKey).slice(0,120),quantity:Math.max(1,Number(input.quantity)||1),idempotency_key:key,actor_id:s.userId||'merchant'}); await audit(s,'customer.membership.benefit.redeem','membership_redemption',row.id,{benefitKey}); return {duplicate:false,id:row.id,benefitKey,quantity:row.quantity}; }
  async function marketingAudienceList(s){ return read('marketing_audiences',s,'order=created_at.desc'); }
  async function marketingOffers(s){ return read('marketing_offers',s,'order=created_at.desc'); }
  async function marketingCampaigns(s){ return read('marketing_campaigns',s,'order=created_at.desc'); }
  async function marketingAudienceMembers(s,audienceId){ const a=first(await read('marketing_audiences',s,`id=eq.${enc(audienceId)}&limit=1`)); if(!a)throw Object.assign(new Error('受众不存在'),{status:404,code:'AUDIENCE_NOT_FOUND'}); const customers=await read('customers',s,'status=eq.active'); const c=a.criteria||{}; const [points,memberships,links]=await Promise.all([read('customer_points_accounts',s,''),read('customer_memberships',s,'status=eq.active'),read('customer_tag_links',s,'')]); const byCustomer=new Map(points.map(x=>[String(x.customer_id),Number(x.balance||0)])); const memberByCustomer=new Map(memberships.map(x=>[String(x.customer_id),String(x.level_id)])); const tagged=new Set(links.filter(x=>String(x.tag_id)===String(c.tagId)).map(x=>String(x.customer_id))); return customers.filter(x=>(c.minPoints==null||byCustomer.get(String(x.id))>=Number(c.minPoints))&&(c.minAppointments==null||Number(x.appointment_count||0)>=Number(c.minAppointments))&&(c.customerStatus==null||x.status===c.customerStatus)&&(c.tagId==null||tagged.has(String(x.id)))&&(c.membershipLevelId==null||memberByCustomer.get(String(x.id))===String(c.membershipLevelId))); }
  async function marketingAnalytics(s,campaignId){ const row=first(await read('marketing_campaigns',s,`id=eq.${enc(campaignId)}&limit=1`)); if(!row)throw Object.assign(new Error('活动不存在'),{status:404,code:'CAMPAIGN_NOT_FOUND'}); const issuances=await read('marketing_issuances',s,`offer_id=eq.${enc(row.offer_id)}`); const redemptions=await read('marketing_redemptions',s,''); const audienceSize=row.audience_id?(await marketingAudienceMembers(s,row.audience_id)).length:0; const issued=issuances.length, redeemed=redemptions.filter(x=>issuances.some(i=>String(i.id)===String(x.issuance_id))).length; return {campaignId,audienceSize,issued,redeemed,redemptionRate:issued?redeemed/issued:0,status:row.status,outboundDeliveryProvider:'NOT_IN_V1'}; }
  async function marketingCreate(s,kind,input={}) { const table=kind==='audience'?'marketing_audiences':kind==='offer'?'marketing_offers':'marketing_campaigns'; const row={id:id(),tenant_id:s.tenantId,workspace_id:s.workspaceId,store_id:s.storeId,created_by:s.userId||'merchant'}; if(kind==='audience'){row.name=String(input.name||'').trim().slice(0,120);row.criteria=input.criteria||{};row.status='draft';} else if(kind==='offer'){row.code=String(input.code||'').trim().slice(0,80);row.name=String(input.name||'').trim().slice(0,120);row.description=String(input.description||'').slice(0,500);row.starts_at=input.startsAt||null;row.expires_at=input.expiresAt||null;row.max_uses=input.maxUses==null?null:Number(input.maxUses);row.single_use=input.singleUse!==false;row.status='draft';} else {row.name=String(input.name||'').trim().slice(0,120);row.audience_id=input.audienceId||null;row.offer_id=input.offerId||null;row.starts_at=input.startsAt||null;row.ends_at=input.endsAt||null;row.status='draft';} if(!row.name || (kind==='offer'&&!row.code)) throw Object.assign(new Error('必填字段缺失'),{status:400,code:'MARKETING_FIELDS_REQUIRED'}); const saved=await insert(table,row); await audit(s,`marketing.${kind}.create`,`marketing_${kind}`,saved.id,{}); return saved; }
  async function marketingUpdate(s,kind,itemId,input={}) {
    const table=kind==='audience'?'marketing_audiences':kind==='offer'?'marketing_offers':'marketing_campaigns';
    const current=first(await read(table,s,`id=eq.${enc(itemId)}&limit=1`));
    if(!current) throw Object.assign(new Error('Marketing resource not found'),{status:404,code:`${kind.toUpperCase()}_NOT_FOUND`});
    const patch={updated_at:new Date().toISOString()};
    if(kind==='audience') {
      if(Object.prototype.hasOwnProperty.call(input,'name')) patch.name=String(input.name||'').trim().slice(0,120);
      if(Object.prototype.hasOwnProperty.call(input,'criteria')) patch.criteria=input.criteria||{};
      if(!String((input.name ?? current.name) || '').trim()) throw Object.assign(new Error('Audience name is required'),{status:400,code:'AUDIENCE_NAME_REQUIRED'});
    } else if(kind==='offer') {
      if(Object.prototype.hasOwnProperty.call(input,'name')) patch.name=String(input.name||'').trim().slice(0,120);
      if(Object.prototype.hasOwnProperty.call(input,'code')) patch.code=String(input.code||'').trim().slice(0,80);
      if(Object.prototype.hasOwnProperty.call(input,'description')) patch.description=String(input.description||'').slice(0,500);
      if(Object.prototype.hasOwnProperty.call(input,'startsAt')) patch.starts_at=input.startsAt||null;
      if(Object.prototype.hasOwnProperty.call(input,'expiresAt')) patch.expires_at=input.expiresAt||null;
      if(Object.prototype.hasOwnProperty.call(input,'maxUses')) patch.max_uses=input.maxUses==null?null:Number(input.maxUses);
      if(Object.prototype.hasOwnProperty.call(input,'singleUse')) patch.single_use=input.singleUse!==false;
      if(!String((input.name ?? current.name) || '').trim() || !String((input.code ?? current.code) || '').trim()) throw Object.assign(new Error('Offer code and name are required'),{status:400,code:'OFFER_FIELDS_REQUIRED'});
    } else {
      if(Object.prototype.hasOwnProperty.call(input,'name')) patch.name=String(input.name||'').trim().slice(0,120);
      if(Object.prototype.hasOwnProperty.call(input,'audienceId')) patch.audience_id=input.audienceId||null;
      if(Object.prototype.hasOwnProperty.call(input,'offerId')) patch.offer_id=input.offerId||null;
      if(Object.prototype.hasOwnProperty.call(input,'startsAt')) patch.starts_at=input.startsAt||null;
      if(Object.prototype.hasOwnProperty.call(input,'endsAt')) patch.ends_at=input.endsAt||null;
      if(!String((input.name ?? current.name) || '').trim()) throw Object.assign(new Error('Campaign name is required'),{status:400,code:'CAMPAIGN_NAME_REQUIRED'});
    }
    const row=await update(table,qscope(s,`id=eq.${enc(itemId)}`),patch); await audit(s,`marketing.${kind}.update`,`marketing_${kind}`,row.id,{}); return row;
  }
  async function marketingStatus(s,kind,itemId,status){const table=kind==='offer'?'marketing_offers':'marketing_campaigns'; const allowed=kind==='offer'?['draft','active','disabled','expired']:['draft','scheduled','active','paused','completed','archived']; if(!allowed.includes(status))throw Object.assign(new Error('状态无效'),{status:400,code:'MARKETING_STATUS_INVALID'}); const row=await update(table,qscope(s,`id=eq.${enc(itemId)}`),{status,updated_at:new Date().toISOString()}); if(!row)throw Object.assign(new Error('Marketing resource not found'),{status:404,code:'MARKETING_NOT_FOUND'}); await audit(s,`marketing.${kind}.${status}`,`marketing_${kind}`,row.id,{status}); return row; }
  async function marketingIssue(s,offerId,customerId,input={}){const key=String(input.idempotencyKey||'').trim();if(!key)throw Object.assign(new Error('缺少幂等键'),{status:400,code:'IDEMPOTENCY_REQUIRED'});const offer=first(await read('marketing_offers',s,`id=eq.${enc(offerId)}&limit=1`));const customer=first(await read('customers',s,`id=eq.${enc(customerId)}&limit=1`));if(!offer)throw Object.assign(new Error('优惠不存在'),{status:404,code:'OFFER_NOT_FOUND'});if(!customer)throw Object.assign(new Error('客户不存在'),{status:404,code:'CUSTOMER_NOT_FOUND'});const existing=first(await read('marketing_issuances',s,`idempotency_key=eq.${enc(key)}&limit=1`));if(existing)return {duplicate:true,...existing};const row=await insert('marketing_issuances',{id:id(),tenant_id:s.tenantId,workspace_id:s.workspaceId,store_id:s.storeId,offer_id:offerId,customer_id:customerId,idempotency_key:key,expires_at:offer.expires_at,actor_id:s.userId||'merchant'});await audit(s,'marketing.offer.issue','marketing_issuance',row.id,{offerId,customerId});return {duplicate:false,...row};}
  async function marketingRedeem(s,issuanceId,input={}){const key=String(input.idempotencyKey||'').trim();if(!key)throw Object.assign(new Error('缺少幂等键'),{status:400,code:'IDEMPOTENCY_REQUIRED'});const issuance=first(await read('marketing_issuances',s,`id=eq.${enc(issuanceId)}&limit=1`));if(!issuance)throw Object.assign(new Error('发放记录不存在'),{status:404,code:'ISSUANCE_NOT_FOUND'});if(issuance.status!=='issued')throw Object.assign(new Error('发放记录不可兑换'),{status:409,code:'ISSUANCE_NOT_REDEEMABLE'});const existing=first(await read('marketing_redemptions',s,`issuance_id=eq.${enc(issuanceId)}&limit=1`));if(existing)return {duplicate:true,...existing};const row=await insert('marketing_redemptions',{id:id(),tenant_id:s.tenantId,workspace_id:s.workspaceId,store_id:s.storeId,issuance_id:issuanceId,customer_id:issuance.customer_id,idempotency_key:key,actor_id:s.userId||'merchant'});await update('marketing_issuances',qscope(s,`id=eq.${enc(issuanceId)}`),{status:'redeemed',redeemed_at:new Date().toISOString()});await audit(s,'marketing.offer.redeem','marketing_redemption',row.id,{issuanceId});return {duplicate:false,...row};}
  async function workflowRegister(s,input){const workflowKey=String(input.workflowKey||'').trim();const name=String(input.name||workflowKey).trim().slice(0,160);const tasks=Array.isArray(input.definition?.tasks)?input.definition.tasks:Array.isArray(input.tasks)?input.tasks:[];if(!/^[A-Za-z0-9][A-Za-z0-9_.-]{0,79}$/.test(workflowKey)||!name||!tasks.length)throw Object.assign(new Error('Workflow 定义无效'),{status:400,code:'WORKFLOW_DEFINITION_INVALID'});const existing=first(await read('workflow_definitions',s,`workflow_key=eq.${enc(workflowKey)}&limit=1`));if(existing)throw Object.assign(new Error('Workflow 定义已存在'),{status:409,code:'WORKFLOW_DEFINITION_EXISTS'});const definitionId=id(),versionId=id();const definition=await insert('workflow_definitions',{id:definitionId,tenant_id:s.tenantId,workspace_id:s.workspaceId,workflow_key:workflowKey,name,created_by:s.userId});try{await insert('workflow_versions',{id:versionId,definition_id:definitionId,tenant_id:s.tenantId,workspace_id:s.workspaceId,version:1,definition_json:{tasks},created_by:s.userId});}catch(error){try{await adapter.deleteResource('workflow_definitions',wqscope(s,`id=eq.${enc(definitionId)}`));}catch{} throw error;}await audit(s,'workflow.definition.register','workflow_definition',definitionId,{workflowKey,version:1});return {definitionId,versionId,workflowKey,name,version:1,tasks};}
  async function workflowDefinitions(s) {
    const rows=await read('workflow_definitions',s,'order=created_at.desc');
    return Promise.all(rows.map(async d=>{const v=first(await read('workflow_versions',s,`definition_id=eq.${enc(d.id)}&order=version.desc&limit=1`));const instances=await read('workflow_instances',s,`definition_id=eq.${enc(d.id)}`);return {id:d.id,workflowKey:d.workflow_key,name:d.name,status:d.status,createdBy:d.created_by,createdAt:d.created_at,updatedAt:d.updated_at,latestVersionId:v?.id||null,latestVersion:v?.version==null?null:Number(v.version),latestVersionStatus:v?.status||null,taskCount:Array.isArray(v?.definition_json?.tasks)?v.definition_json.tasks.length:0,instanceCount:instances.length};}));
  }
  async function workflowRuns(s,limit=50){const rows=await read('workflow_instances',s,`order=updated_at.desc&limit=${Math.min(100,Math.max(1,Number(limit)||50))}`);return Promise.all(rows.map(async r=>{const d=first(await read('workflow_definitions',s,`id=eq.${enc(r.definition_id)}&limit=1`));const events=await read('workflow_events',s,`instance_id=eq.${enc(r.id)}&order=created_at.desc&limit=1`);const tasks=await read('workflow_tasks',s,`instance_id=eq.${enc(r.id)}&status=eq.failed`);return {id:r.id,workflowKey:d?.workflow_key||null,status:r.status,context:r.context,startedAt:r.started_at,completedAt:r.completed_at,updatedAt:r.updated_at,lastEventAt:events[0]?.created_at||null,failedTasks:tasks.length};}));}
  async function workflowCancel(s,instanceId){const i=first(await read('workflow_instances',s,`id=eq.${enc(instanceId)}&limit=1`));if(!i)throw Object.assign(new Error('Workflow 实例不存在'),{status:404,code:'WORKFLOW_INSTANCE_NOT_FOUND'});if(i.status!=='running')throw Object.assign(new Error('Workflow 实例当前不可取消'),{status:409,code:'WORKFLOW_INSTANCE_NOT_RUNNING'});await update('workflow_tasks',wqscope(s,`instance_id=eq.${enc(instanceId)}&status=eq.pending`),{status:'cancelled'});await update('workflow_instances',wqscope(s,`id=eq.${enc(instanceId)}`),{status:'cancelled',completed_at:new Date().toISOString(),updated_at:new Date().toISOString()});await workflowEvent(s,instanceId,null,'instance.cancelled',{});return workflowLoad(s,instanceId);}
  async function workflowStatus(s,key,status){if(!['active','archived'].includes(status))throw Object.assign(new Error('Workflow 状态无效'),{status:400,code:'WORKFLOW_STATUS_INVALID'});const row=await update('workflow_definitions',wqscope(s,`workflow_key=eq.${enc(key)}`),{status,updated_at:new Date().toISOString()});if(!row)throw Object.assign(new Error('Workflow 定义不存在'),{status:404,code:'WORKFLOW_DEFINITION_NOT_FOUND'});await audit(s,`workflow.definition.${status}`,'workflow_definition',row.id,{workflowKey:key,status});return {id:row.id,workflowKey:row.workflow_key,name:row.name,status:row.status,updatedAt:row.updated_at};}
  async function workflowLoad(s,instanceId){const i=first(await read('workflow_instances',s,`id=eq.${enc(instanceId)}&limit=1`));if(!i)throw Object.assign(new Error('Workflow 实例不存在'),{status:404,code:'WORKFLOW_INSTANCE_NOT_FOUND'});const d=first(await read('workflow_definitions',s,`id=eq.${enc(i.definition_id)}&limit=1`));const v=first(await read('workflow_versions',s,`id=eq.${enc(i.version_id)}&limit=1`));const tasks=await read('workflow_tasks',s,`instance_id=eq.${enc(instanceId)}&order=created_at.asc`);const events=await read('workflow_events',s,`instance_id=eq.${enc(instanceId)}&order=sequence.asc`);return {id:i.id,workflowKey:d?.workflow_key,name:d?.name,definitionId:i.definition_id,versionId:i.version_id,version:v?.version,status:i.status,context:i.context,idempotencyKey:i.idempotency_key,startedBy:i.started_by,startedAt:i.started_at,completedAt:i.completed_at,updatedAt:i.updated_at,tasks:tasks.map(t=>({id:t.id,taskKey:t.task_key,taskType:t.task_type,status:t.status,input:t.input,output:t.output,assignedUserId:t.assigned_user_id,createdAt:t.created_at,completedAt:t.completed_at})),events:events.map(e=>({id:e.id,sequence:e.sequence,eventType:e.event_type,taskId:e.task_id,actorId:e.actor_id,payload:e.payload,createdAt:e.created_at}))};}
  async function workflowEvent(s,instanceId,taskId,type,payload,sequenceOverride=null){const i=sequenceOverride==null?first(await read('workflow_instances',s,`id=eq.${enc(instanceId)}&limit=1`)):true;if(!i)throw Object.assign(new Error('Workflow 实例不存在'),{status:404,code:'WORKFLOW_INSTANCE_NOT_FOUND'});const sequence=sequenceOverride==null?Number(i.next_event_sequence||1):Number(sequenceOverride);await update('workflow_instances',wqscope(s,`id=eq.${enc(instanceId)}`),{next_event_sequence:sequence+1,updated_at:new Date().toISOString()});const row=await insert('workflow_events',{id:id(),instance_id:instanceId,task_id:taskId||null,tenant_id:s.tenantId,workspace_id:s.workspaceId,sequence,event_type:type,actor_id:s.userId||'system',payload});await audit({...s,requestId:`${s.requestId||id()}:workflow:${instanceId}:${sequence}`},`workflow.${type}`,'workflow_instance',instanceId,{...payload,sequence});return row;}
  async function workflowStart(s,input){const key=String(input.workflowKey||'').trim();if(!key)throw Object.assign(new Error('缺少 Workflow 标识'),{status:400,code:'WORKFLOW_KEY_REQUIRED'});const d=first(await read('workflow_definitions',s,`workflow_key=eq.${enc(key)}&status=eq.active&limit=1`));if(!d)throw Object.assign(new Error('Workflow 定义不存在'),{status:404,code:'WORKFLOW_DEFINITION_NOT_FOUND'});const v=first(await read('workflow_versions',s,`definition_id=eq.${enc(d.id)}&status=eq.published&order=version.desc&limit=1`));if(!v)throw Object.assign(new Error('Workflow 版本不存在'),{status:404,code:'WORKFLOW_DEFINITION_NOT_FOUND'});const idem=input.idempotencyKey?String(input.idempotencyKey):null;if(idem){const existing=first(await read('workflow_instances',s,`idempotency_key=eq.${enc(idem)}&limit=1`));if(existing)return {created:false,instance:await workflowLoad(s,existing.id)};}const instance=await insert('workflow_instances',{id:id(),definition_id:d.id,version_id:v.id,tenant_id:s.tenantId,workspace_id:s.workspaceId,status:'running',context:input.context||{},idempotency_key:idem,started_by:s.userId});const tasks=Array.isArray(v.definition_json?.tasks)?v.definition_json.tasks:[];const firstTask=tasks[0];const task=await insert('workflow_tasks',{id:id(),instance_id:instance.id,definition_id:d.id,tenant_id:s.tenantId,workspace_id:s.workspaceId,task_key:firstTask.key,task_type:firstTask.type||'manual',status:'pending',input:{title:firstTask.title||firstTask.key}});await insert('workflow_events',{id:id(),instance_id:instance.id,task_id:null,tenant_id:s.tenantId,workspace_id:s.workspaceId,sequence:1,event_type:'instance.started',actor_id:s.userId||'system',payload:{workflowKey:key,version:v.version}});await audit({...s,requestId:`${s.requestId||id()}:workflow:${instance.id}:1`},'workflow.instance.started','workflow_instance',instance.id,{workflowKey:key,version:v.version,sequence:1});await insert('workflow_events',{id:id(),instance_id:instance.id,task_id:task.id,tenant_id:s.tenantId,workspace_id:s.workspaceId,sequence:2,event_type:'task.ready',actor_id:s.userId||'system',payload:{taskKey:firstTask.key,taskType:firstTask.type||'manual'}});await audit({...s,requestId:`${s.requestId||id()}:workflow:${instance.id}:2`},'workflow.task.ready','workflow_instance',instance.id,{taskKey:firstTask.key,taskType:firstTask.type||'manual',sequence:2});await update('workflow_instances',wqscope(s,`id=eq.${enc(instance.id)}`),{next_event_sequence:3,updated_at:new Date().toISOString()});return {created:true,instance:await workflowLoad(s,instance.id)};}
  async function workflowTask(s,instanceId,taskKey,action,input={}){const instance=first(await read('workflow_instances',s,`id=eq.${enc(instanceId)}&limit=1`));if(!instance)throw Object.assign(new Error('Workflow 实例不存在'),{status:404,code:'WORKFLOW_INSTANCE_NOT_FOUND'});const task=first(await read('workflow_tasks',s,`instance_id=eq.${enc(instanceId)}&task_key=eq.${enc(taskKey)}&limit=1`));if(!task)throw Object.assign(new Error('Workflow 任务不存在'),{status:404,code:'WORKFLOW_TASK_NOT_FOUND'});if(action==='complete'){if(instance.status!=='running'||task.status!=='pending')throw Object.assign(new Error('Workflow 任务当前不可完成'),{status:409,code:'WORKFLOW_TASK_NOT_PENDING'});let sequence=Number(instance.next_event_sequence||1);await update('workflow_tasks',wqscope(s,`id=eq.${enc(task.id)}`),{status:'completed',output:input.output||{},completed_at:new Date().toISOString()});const v=first(await read('workflow_versions',s,`id=eq.${enc(instance.version_id)}&limit=1`));const defs=v?.definition_json?.tasks||[];const next=defs[defs.findIndex(x=>x.key===taskKey)+1];await workflowEvent(s,instanceId,task.id,'task.completed',{taskKey},sequence++);if(next){const nextTask=await insert('workflow_tasks',{id:id(),instance_id:instanceId,definition_id:instance.definition_id,tenant_id:s.tenantId,workspace_id:s.workspaceId,task_key:next.key,task_type:next.type||'manual',status:'pending',input:{title:next.title||next.key}});await workflowEvent(s,instanceId,nextTask.id,'task.ready',{taskKey:next.key,taskType:next.type||'manual'},sequence++);}else{await update('workflow_instances',wqscope(s,`id=eq.${enc(instanceId)}`),{status:'completed',completed_at:new Date().toISOString(),updated_at:new Date().toISOString()});await workflowEvent(s,instanceId,null,'instance.completed',{},sequence++);} }
    else if(action==='fail'){if(task.status!=='pending')throw Object.assign(new Error('Workflow 任务当前不可失败'),{status:409,code:'WORKFLOW_TASK_NOT_PENDING'});const retryCount=Number(task.retry_count||0)+1;await update('workflow_tasks',wqscope(s,`id=eq.${enc(task.id)}`),{status:'failed',retry_count:retryCount,last_error:String(input.reason||'执行失败').slice(0,500),completed_at:new Date().toISOString()});await update('workflow_instances',wqscope(s,`id=eq.${enc(instanceId)}`),{status:'failed',updated_at:new Date().toISOString()});await workflowEvent(s,instanceId,task.id,'task.failed',{taskKey,reason:input.reason||'执行失败',retryCount,retryLimit:Number(task.retry_limit||3)});}
    else if(action==='retry'){if(task.status!=='failed')throw Object.assign(new Error('Workflow 任务当前不可重试'),{status:409,code:'WORKFLOW_TASK_NOT_FAILED'});if(Number(task.retry_count||0)>=Number(task.retry_limit||3))throw Object.assign(new Error('已达到重试上限'),{status:409,code:'WORKFLOW_RETRY_EXHAUSTED'});await update('workflow_tasks',wqscope(s,`id=eq.${enc(task.id)}`),{status:'pending',completed_at:null});await update('workflow_instances',wqscope(s,`id=eq.${enc(instanceId)}`),{status:'running',updated_at:new Date().toISOString()});await workflowEvent(s,instanceId,task.id,'task.retrying',{taskKey,retryCount:Number(task.retry_count||0)});}
    return workflowLoad(s,instanceId);
  }
  return {customerTagLink,membershipActivity,membershipRule,membershipEvaluate,membershipOverride,membershipRedeem,marketingAudienceList,marketingAudienceMembers,marketingOffers,marketingCampaigns,marketingAnalytics,marketingCreate,marketingUpdate,marketingStatus,marketingIssue,marketingRedeem,workflowRegister,workflowDefinitions,workflowRuns,workflowStatus,workflowStart,workflowTask,workflowCancel,workflowLoad};
}
module.exports={createMeooLaunchV1Repository};
