// Generated by PRIVLAN Commerce Studio. Edit the homepage in the admin panel.
Page({
  data: {
    "navPadTop": 20,
    "channels": [
        "推荐",
        "LAKE MAGGIORE"
    ],
    "channel": "推荐",
    "pageTitle": "我的",
    "cartItems": [],
    "cartSummary": {
        "quantity": 0,
        "price": 0
    },
    "serviceBot": {
        "enabled": true,
        "icon": "/images/icon-headset.png",
        "size": 88,
        "right": 110,
        "bottom": 475
    },
    "block0Hotspots": [],
    "block0": [
        {
            "icon": "/images/svc-presale.png",
            "text": "新品预售",
            "linkType": "page",
            "linkValue": "/pages/category/category?cat=new"
        },
        {
            "icon": "/images/svc-cs.png",
            "text": "专属客服",
            "linkType": "page",
            "linkValue": "/pages/service-chat/index"
        },
        {
            "icon": "/images/svc-tailor.png",
            "text": "改衣服务",
            "linkType": "page",
            "linkValue": "/pages/appointment/index"
        },
        {
            "icon": "/images/svc-gift.png",
            "text": "尊享礼遇",
            "linkType": "page",
            "linkValue": "/pages/mine/mine"
        }
    ],
    "block1Hotspots": [],
    "block2Hotspots": [],
    "block2": [
        {
            "id": 6,
            "cat": "tops",
            "name": "0004",
            "price": 4900,
            "img": "/images/41b7d4277afa3c44ee45d3606b761c6e.jpg",
            "gallery": [
                "/images/41b7d4277afa3c44ee45d3606b761c6e.jpg"
            ],
            "colors": [],
            "sizes": [],
            "description": "",
            "detail": "",
            "detailImages": []
        },
        {
            "id": 5,
            "cat": "tops",
            "name": "0003",
            "price": 4900,
            "img": "/images/Kith_Giorgio_Armani__The_Archetype_Lookbook.jpeg",
            "gallery": [
                "/images/Kith_Giorgio_Armani__The_Archetype_Lookbook.jpeg"
            ],
            "colors": [],
            "sizes": [
                "新尺码"
            ],
            "description": "",
            "detail": "",
            "detailImages": []
        },
        {
            "id": 4,
            "cat": "tops",
            "name": "0002",
            "price": 4900,
            "img": "/images/29_0df4a244-de71-4b8a-a8c4-69ecaef14d83.jpeg",
            "gallery": [
                "/images/29_0df4a244-de71-4b8a-a8c4-69ecaef14d83.jpeg"
            ],
            "colors": [],
            "sizes": [],
            "description": "",
            "detail": "",
            "detailImages": []
        },
        {
            "id": 3,
            "cat": "tops",
            "name": "0001",
            "price": 4900,
            "img": "/images/7_33529103-a9a4-4ed2-bc1b-2dbca5c4bb89.jpeg",
            "gallery": [
                "/images/7_33529103-a9a4-4ed2-bc1b-2dbca5c4bb89.jpeg"
            ],
            "colors": [],
            "sizes": [],
            "description": "",
            "detail": "",
            "detailImages": []
        }
    ]
},
  onLoad() {
    const win = wx.getWindowInfo ? wx.getWindowInfo() : wx.getSystemInfoSync();
    const menu = wx.getMenuButtonBoundingClientRect();
    this.setData({ navPadTop: menu.top || win.statusBarHeight || 20 });
  },
  onShow() {
    if (typeof this.getTabBar === "function" && this.getTabBar()) this.getTabBar().setData({ selected: 4 });
  },
  switchChannel(e) { this.setData({ channel: e.currentTarget.dataset.c }); },
  onSearch() { wx.showToast({ title: "搜索功能演示", icon: "none" }); },
  heroAction(e) {
    const type = e.currentTarget.dataset.linkType;
    const value = e.currentTarget.dataset.linkValue;
    if (!value) return;
    const clean = value.split("?")[0];
    const tabs = ["/pages/home/home", "/pages/category/category", "/pages/campaign/campaign", "/pages/cart/cart", "/pages/mine/mine"];
    if (tabs.includes(clean)) wx.switchTab({ url: clean });
    else if (type === "external") wx.navigateTo({ url: "/pages/webview/webview?url=" + encodeURIComponent(value) });
    else wx.navigateTo({ url: value });
  },
  mediaAction(e) { this.heroAction(e); },
  benefitAction(e) { this.heroAction(e); },
  hotspotAction(e) { this.heroAction(e); },
  explore() { wx.switchTab({ url: "/pages/category/category" }); },
  goDetail(e) { wx.navigateTo({ url: "/pages/detail/detail?id=" + e.currentTarget.dataset.id }); },
  goBack() { wx.navigateBack({ fail: () => wx.switchTab({ url: "/pages/home/home" }) }); },
  addCart() { cart.add(null); this.refreshCart(); wx.showToast({ title: "已加入购物车", icon: "success" }); },
  buyNow() { cart.add(null); wx.switchTab({ url: "/pages/cart/cart" }); }
});
