// Generated by PRIVLAN Commerce Studio.
module.exports = {
  "kicker": "PRIVLAN APPOINTMENT",
  "title": "预约专属服务",
  "description": "选择适合你的门店、时间和顾问，我们会提前做好准备。",
  "submitText": "确认预约",
  "successTitle": "预约已提交",
  "successCopy": "我们会尽快确认你的预约，请留意顾问联系。",
  "notesLabel": "到店备注",
  "notesPlaceholder": "可填写想了解的款式、场合或其他需求",
  "fields": {
    "name": true,
    "phone": true,
    "service": false,
    "store": false,
    "date": true,
    "time": true,
    "advisor": false,
    "notes": true
  }
};
