// Generated by PRIVLAN Commerce Studio.
module.exports = {
  "enabled": true,
  "icon": "/images/icon-headset.png",
  "size": 88,
  "right": 110,
  "bottom": 475,
  "welcomeMessage": "您好，我是 PRIVLAN 专属服务助手。请问今天想了解什么？",
  "quickPrompts": [
    "我要预约",
    "你们的价格区间是多少？",
    "你们用的什么面料？",
    "版型与款式",
    "制作周期多久？",
    "转人工服务"
  ],
  "answerProvider": "rules",
  "humanServiceEnabled": false,
  "authMode": "test"
};
